/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The acceleration of this engine.
 */
export interface Acceleration { 
    /**
     * The value of this acceleration.
     */
    value: number;
    /**
     * The metric of this acceleration.
     */
    accelerationMetric: Acceleration.AccelerationMetricEnum;
    /**
     * The hyper band which can be reached.
     */
    hyperBand: Acceleration.HyperBandEnum;
}
export namespace Acceleration {
    export type AccelerationMetricEnum = 'MS2' | 'G' | 'C';
    export const AccelerationMetricEnum = {
        MS2: 'MS2' as AccelerationMetricEnum,
        G: 'G' as AccelerationMetricEnum,
        C: 'C' as AccelerationMetricEnum
    };
    export type HyperBandEnum = 'NONE' | 'ALPHA' | 'BETA' | 'GAMMA' | 'DELTA' | 'EPSILON' | 'ZETA' | 'ETA' | 'THETA';
    export const HyperBandEnum = {
        NONE: 'NONE' as HyperBandEnum,
        ALPHA: 'ALPHA' as HyperBandEnum,
        BETA: 'BETA' as HyperBandEnum,
        GAMMA: 'GAMMA' as HyperBandEnum,
        DELTA: 'DELTA' as HyperBandEnum,
        EPSILON: 'EPSILON' as HyperBandEnum,
        ZETA: 'ZETA' as HyperBandEnum,
        ETA: 'ETA' as HyperBandEnum,
        THETA: 'THETA' as HyperBandEnum
    };
}
