/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface ArticleCreate { 
    /**
     * The title
     */
    title: string;
    /**
     * The category
     */
    wikiCategory: ArticleCreate.WikiCategoryEnum;
    /**
     * The tutorial category
     */
    tutorialCategory?: ArticleCreate.TutorialCategoryEnum;
    /**
     * The content
     */
    content: string;
    /**
     * The language this article is for
     */
    langCode: string;
}
export namespace ArticleCreate {
    export type WikiCategoryEnum = 'WELCOME_MESSAGE' | 'MISSION_TYPES' | 'GAME_MECHANICS';
    export const WikiCategoryEnum = {
        WELCOME_MESSAGE: 'WELCOME_MESSAGE' as WikiCategoryEnum,
        MISSION_TYPES: 'MISSION_TYPES' as WikiCategoryEnum,
        GAME_MECHANICS: 'GAME_MECHANICS' as WikiCategoryEnum
    };
    export type TutorialCategoryEnum = 'FLEET_DASH' | 'JOB_DASH' | 'TRADE_DASH' | 'INFRA_DASH' | 'BATTLE_DASH' | 'PLANET_DASH' | 'PLANET_CONSTRUCTIONS' | 'PLANET_SHIPYARD' | 'MARKETPLACE' | 'INNER_EMPIRE_TRANSPORTATION' | 'UNIVERSE_MAP' | 'STAR_MAP' | 'MISSION' | 'COLONIZATION_INFO' | 'FLEET_DETACHMENT';
    export const TutorialCategoryEnum = {
        FLEET_DASH: 'FLEET_DASH' as TutorialCategoryEnum,
        JOB_DASH: 'JOB_DASH' as TutorialCategoryEnum,
        TRADE_DASH: 'TRADE_DASH' as TutorialCategoryEnum,
        INFRA_DASH: 'INFRA_DASH' as TutorialCategoryEnum,
        BATTLE_DASH: 'BATTLE_DASH' as TutorialCategoryEnum,
        PLANET_DASH: 'PLANET_DASH' as TutorialCategoryEnum,
        PLANET_CONSTRUCTIONS: 'PLANET_CONSTRUCTIONS' as TutorialCategoryEnum,
        PLANET_SHIPYARD: 'PLANET_SHIPYARD' as TutorialCategoryEnum,
        MARKETPLACE: 'MARKETPLACE' as TutorialCategoryEnum,
        INNER_EMPIRE_TRANSPORTATION: 'INNER_EMPIRE_TRANSPORTATION' as TutorialCategoryEnum,
        UNIVERSE_MAP: 'UNIVERSE_MAP' as TutorialCategoryEnum,
        STAR_MAP: 'STAR_MAP' as TutorialCategoryEnum,
        MISSION: 'MISSION' as TutorialCategoryEnum,
        COLONIZATION_INFO: 'COLONIZATION_INFO' as TutorialCategoryEnum,
        FLEET_DETACHMENT: 'FLEET_DETACHMENT' as TutorialCategoryEnum
    };
}