/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface ArticleEdit { 
    /**
     * The id of the article to edit
     */
    idArticle: number;
    /**
     * The title
     */
    title?: string;
    /**
     * The category
     */
    wikiCategory?: ArticleEdit.WikiCategoryEnum;
    /**
     * The content
     */
    content?: string;
}
export namespace ArticleEdit {
    export type WikiCategoryEnum = 'WELCOME_MESSAGE' | 'MISSION_TYPES' | 'GAME_MECHANICS';
    export const WikiCategoryEnum = {
        WELCOME_MESSAGE: 'WELCOME_MESSAGE' as WikiCategoryEnum,
        MISSION_TYPES: 'MISSION_TYPES' as WikiCategoryEnum,
        GAME_MECHANICS: 'GAME_MECHANICS' as WikiCategoryEnum
    };
}