/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EModuleType } from './eModuleType';
import { EShipClassType } from './eShipClassType';
import { Mass } from './mass';
import { PropertyDescriptor } from './propertyDescriptor';

/**
 * .
 */
export interface BaseModule { 
    /**
     * The id of this module.
     */
    idModule: number;
    /**
     * The name of this module.
     */
    name: string;
    /**
     * The technical type name of this module.
     */
    technicalTypeName?: string;
    /**
     * The description of this module.
     */
    description: string;
    tonnage?: Mass;
    /**
     * The base effect value of this module.
     */
    effectValue?: number;
    /**
     * The level of this module.
     */
    techLevel: BaseModule.TechLevelEnum;
    shipClassType?: EShipClassType;
    moduleType?: EModuleType;
    propertyDescriptor: PropertyDescriptor;
}
export namespace BaseModule {
    export type TechLevelEnum = 'TECH_I' | 'TECH_II' | 'TECH_III';
    export const TechLevelEnum = {
        I: 'TECH_I' as TechLevelEnum,
        II: 'TECH_II' as TechLevelEnum,
        III: 'TECH_III' as TechLevelEnum
    };
}