/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BaseModule { 
    /**
     * The description of this module.
     */
    description: string;
    /**
     * The base effect value of this module.
     */
    effectValue: number;
    /**
     * The name of this module.
     */
    name: string;
    /**
     * The level of this module.
     */
    techLevel: number;
    /**
     * The capacity usage of this module.
     */
    useCapacity: number;
}