/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CombatRound } from './combatRound';
import { CounterMissileHit } from './counterMissileHit';
import { Fleet } from './fleet';
import { FleetOrbit } from './fleetOrbit';
import { LossRole } from './lossRole';
import { MissileMovement } from './missileMovement';
import { MovementAction } from './movementAction';
import { ReleasedVolley } from './releasedVolley';
import { ShipKillerHit } from './shipKillerHit';
import { Tick } from './tick';
import { UserJson } from './userJson';

export interface BattleReport { 
    /**
     * The hits against missile salvos.
     */
    counterMissileHits: Array<CounterMissileHit>;
    /**
     * The database id of the report.
     */
    idBattleReport: number;
    lastRound: CombatRound;
    /**
     * The losses of this battle.
     */
    lossRole: Array<LossRole>;
    /**
     * The missile movements during this combat.
     */
    missileMovements: Array<MissileMovement>;
    /**
     * The movements which were done in this clash.
     */
    movementActions: Array<MovementAction>;
    orbit: FleetOrbit;
    /**
     * The protagonists - and the antagonists.
     */
    participatingFleets: Array<Fleet>;
    /**
     * The participating users.
     */
    participatingUsers: Array<UserJson>;
    /**
     * All loose off weapon action.
     */
    releasedVolleys: Array<ReleasedVolley>;
    /**
     * All hits of ship killer weapons during this combat.
     */
    shipKillerHits: Array<ShipKillerHit>;
    tick: Tick;
}
