/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BattleReportStatistics } from './battleReportStatistics';
import { CounterMissileHit } from './counterMissileHit';
import { Fleet } from './fleet';
import { LossRole } from './lossRole';
import { MissileMovement } from './missileMovement';
import { MovementAction } from './movementAction';
import { Player } from './player';
import { ReleasedVolley } from './releasedVolley';
import { ShipKillerHit } from './shipKillerHit';

/**
 * .
 */
export interface BattleReport { 
    battleReportStatistics: BattleReportStatistics;
    /**
     * The participating users.
     */
    participatingUsers: Array<Player>;
    /**
     * The protagonists - and the antagonists.
     */
    participatingFleets: Array<Fleet>;
    /**
     * The losses of this battle.
     */
    lossRole: Array<LossRole>;
    /**
     * The movements which were done in this clash.
     */
    movementActions: Array<MovementAction>;
    /**
     * The hits against missile salvos.
     */
    counterMissileHits: Array<CounterMissileHit>;
    /**
     * All loose off weapon action.
     */
    releasedVolleys: Array<ReleasedVolley>;
    /**
     * The missile movements during this combat.
     */
    missileMovements: Array<MissileMovement>;
    /**
     * All hits of ship killer weapons during this combat.
     */
    shipKillerHits: Array<ShipKillerHit>;
}