/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Building { 
    /**
     * The production amount at first level.
     */
    baseValue: number;
    /**
     * The description.
     */
    description: string;
    /**
     * The ID.
     */
    idBuilding: number;
    /**
     * The modification factor per level.
     */
    increasingFactorPerLevel: number;
    /**
     * The name of this building.
     */
    name: string;
    /**
     * The action this building is for.
     */
    productionCategory: Building.ProductionCategoryEnum;
    /**
     * The subject of this building.
     */
    productionTarget: Building.ProductionTargetEnum;
    /**
     * In case of a refinement building - this is the defines sequence.
     */
    refinementSequence?: Building.RefinementSequenceEnum;
}
export namespace Building {
    export type ProductionCategoryEnum = 'CAPACITY' | 'PRODUCE' | 'REFINEMENT';
    export const ProductionCategoryEnum = {
        CAPACITY: 'CAPACITY' as ProductionCategoryEnum,
        PRODUCE: 'PRODUCE' as ProductionCategoryEnum,
        REFINEMENT: 'REFINEMENT' as ProductionCategoryEnum
    };
    export type ProductionTargetEnum = 'CONSTRUCTION' | 'CREDITS' | 'HEAVY_METALS' | 'METALORE' | 'ORBITAL_CONSTRUCTION' | 'POPULATION' | 'RARE_ELEMENTS' | 'RESEARCH';
    export const ProductionTargetEnum = {
        CONSTRUCTION: 'CONSTRUCTION' as ProductionTargetEnum,
        CREDITS: 'CREDITS' as ProductionTargetEnum,
        HEAVYMETALS: 'HEAVY_METALS' as ProductionTargetEnum,
        METALORE: 'METALORE' as ProductionTargetEnum,
        ORBITALCONSTRUCTION: 'ORBITAL_CONSTRUCTION' as ProductionTargetEnum,
        POPULATION: 'POPULATION' as ProductionTargetEnum,
        RAREELEMENTS: 'RARE_ELEMENTS' as ProductionTargetEnum,
        RESEARCH: 'RESEARCH' as ProductionTargetEnum
    };
    export type RefinementSequenceEnum = 'EDUCATION_CIVIL_I' | 'EDUCATION_CIVIL_II' | 'EDUCATION_CIVIL_III' | 'EDUCATION_MILITARY_I' | 'EDUCATION_MILITARY_II';
    export const RefinementSequenceEnum = {
        CIVILI: 'EDUCATION_CIVIL_I' as RefinementSequenceEnum,
        CIVILII: 'EDUCATION_CIVIL_II' as RefinementSequenceEnum,
        CIVILIII: 'EDUCATION_CIVIL_III' as RefinementSequenceEnum,
        MILITARYI: 'EDUCATION_MILITARY_I' as RefinementSequenceEnum,
        MILITARYII: 'EDUCATION_MILITARY_II' as RefinementSequenceEnum
    };
}