/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERefinementSequence } from './eRefinementSequence';
import { EResourceType } from './eResourceType';

export interface Building { 
    /**
     * The production amount at first level.
     */
    baseValue: number;
    /**
     * The description.
     */
    description: string;
    /**
     * The ID.
     */
    idBuilding: number;
    /**
     * The modification factor per level.
     */
    increasingFactorPerLevel: number;
    /**
     * The name of this building.
     */
    name: string;
    /**
     * The action this building is for.
     */
    productionCategory: Building.ProductionCategoryEnum;
    productionTarget: EResourceType;
    refinementSequence?: ERefinementSequence;
}
export namespace Building {
    export type ProductionCategoryEnum = 'CAPACITY' | 'PRODUCE' | 'REFINEMENT';
    export const ProductionCategoryEnum = {
        CAPACITY: 'CAPACITY' as ProductionCategoryEnum,
        PRODUCE: 'PRODUCE' as ProductionCategoryEnum,
        REFINEMENT: 'REFINEMENT' as ProductionCategoryEnum
    };
}