/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERefinementSequence } from './eRefinementSequence';
import { EResourceType } from './eResourceType';

/**
 * .
 */
export interface Building { 
    /**
     * The ID.
     */
    idBuilding: number;
    /**
     * The name of this building.
     */
    name: string;
    /**
     * The description.
     */
    description: string;
    /**
     * The unlocking research name.
     */
    unlockedThrough: string;
    /**
     * The production amount at first level.
     */
    baseValue: number;
    /**
     * The modification factor per level.
     */
    increasingFactorPerLevel: number;
    productionTarget: EResourceType;
    /**
     * The action this building is for.
     */
    productionCategory: Building.ProductionCategoryEnum;
    refinementSequence?: ERefinementSequence;
}
export namespace Building {
    export type ProductionCategoryEnum = 'PRODUCE' | 'CAPACITY' | 'REFINEMENT';
    export const ProductionCategoryEnum = {
        PRODUCE: 'PRODUCE' as ProductionCategoryEnum,
        CAPACITY: 'CAPACITY' as ProductionCategoryEnum,
        REFINEMENT: 'REFINEMENT' as ProductionCategoryEnum
    };
}