/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Mass } from './mass';

/**
 * .
 */
export interface CapacityValue { 
    /**
     * The value's type.
     */
    capacityArea: CapacityValue.CapacityAreaEnum;
    tonnage: Mass;
}
export namespace CapacityValue {
    export type CapacityAreaEnum = 'OVERALL' | 'STERN' | 'BROADSIDE' | 'BOW' | 'MODULE';
    export const CapacityAreaEnum = {
        OVERALL: 'OVERALL' as CapacityAreaEnum,
        STERN: 'STERN' as CapacityAreaEnum,
        BROADSIDE: 'BROADSIDE' as CapacityAreaEnum,
        BOW: 'BOW' as CapacityAreaEnum,
        MODULE: 'MODULE' as CapacityAreaEnum
    };
}