/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface ChangeSharedBattleReport { 
    /**
     * .
     */
    idBattleReport: number;
    /**
     * .
     */
    sharedWithAlliance?: number;
    /**
     * .
     */
    sharedWithUser?: number;
    /**
     * .
     */
    shareWithEveryone?: boolean;
    /**
     * What should be done
     */
    calculationType: ChangeSharedBattleReport.CalculationTypeEnum;
}
export namespace ChangeSharedBattleReport {
    export type CalculationTypeEnum = 'NONE' | 'ADD' | 'SUBTRACT';
    export const CalculationTypeEnum = {
        NONE: 'NONE' as CalculationTypeEnum,
        ADD: 'ADD' as CalculationTypeEnum,
        SUBTRACT: 'SUBTRACT' as CalculationTypeEnum
    };
}