/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatMessage } from './chatMessage';
import { UserJson } from './userJson';

export interface ChatHistory { 
    /**
     * The id of this chat history
     */
    idChatHistory?: number;
    /**
     * The amount of messages.
     */
    messages: Array<ChatMessage>;
    userOne: UserJson;
    userTwo: UserJson;
}