/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Planet } from './planet';
import { UserJson } from './userJson';

export interface Colonization { 
    /**
     * The amount of ticks to complete colonization.
     */
    doneAtZero: number;
    /**
     * The id of the colonization.
     */
    idColonization: number;
    target: Planet;
    user: UserJson;
}