/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Building } from './building';

export interface Construction { 
    building: Building;
    /**
     * The ID of this construction.
     */
    idConstruction: number;
    /**
     * The level of this construction.
     */
    level: number;
}