/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConvoyRaidActionItem } from './convoyRaidActionItem';
import { TradeContract } from './tradeContract';

/**
 * .
 */
export interface ConvoyRaidActionItemGroup { 
    /**
     * What happens.
     */
    missionType: ConvoyRaidActionItemGroup.MissionTypeEnum;
    affectedTrade: TradeContract;
    /**
     * The actions to report.
     */
    actionItems: Array<ConvoyRaidActionItem>;
}
export namespace ConvoyRaidActionItemGroup {
    export type MissionTypeEnum = 'PIRATE_RAID' | 'PIRATE_HUNT' | 'CONVOY_PROTECTION' | 'CONVOY_RAID';
    export const MissionTypeEnum = {
        PIRATE_RAID: 'PIRATE_RAID' as MissionTypeEnum,
        PIRATE_HUNT: 'PIRATE_HUNT' as MissionTypeEnum,
        CONVOY_PROTECTION: 'CONVOY_PROTECTION' as MissionTypeEnum,
        CONVOY_RAID: 'CONVOY_RAID' as MissionTypeEnum
    };
}