/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface Distance { 
    /**
     * The value of this distance.
     */
    coordinate: number;
    /**
     * The metric of this distance.
     */
    distanceMetric: Distance.DistanceMetricEnum;
}
export namespace Distance {
    export type DistanceMetricEnum = 'M' | 'KM' | 'LS' | 'LM' | 'AU' | 'LH' | 'LD' | 'LY' | 'PC';
    export const DistanceMetricEnum = {
        M: 'M' as DistanceMetricEnum,
        KM: 'KM' as DistanceMetricEnum,
        LS: 'LS' as DistanceMetricEnum,
        LM: 'LM' as DistanceMetricEnum,
        AU: 'AU' as DistanceMetricEnum,
        LH: 'LH' as DistanceMetricEnum,
        LD: 'LD' as DistanceMetricEnum,
        LY: 'LY' as DistanceMetricEnum,
        PC: 'PC' as DistanceMetricEnum
    };
}