/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EHullType { 
    /**
     * If the hull is an auxiliary ship.
     */
    auxiliaryShip: boolean;
    /**
     * The hulls description.
     */
    description: string;
    /**
     * The folder name for resources.
     */
    folder: string;
    /**
     * The icon name for this resource.
     */
    iconName: string;
    /**
     * If the hull is a pod layer.
     */
    podLayer: boolean;
    /**
     * The hulls type.
     */
    type: string;
    /**
     * The hull types type name.
     */
    typeName: string;
}