/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EModuleTypeToIcon { 
    /**
     * The icon name.
     */
    iconName: string;
    /**
     * The module type.
     */
    moduleType: EModuleTypeToIcon.ModuleTypeEnum;
}
export namespace EModuleTypeToIcon {
    export type ModuleTypeEnum = 'ARMOR' | 'ELECTRONIC_WARFARE' | 'FTLPROPULSION' | 'PROPULSION' | 'SHIELD' | 'WEAPON';
    export const ModuleTypeEnum = {
        ARMOR: 'ARMOR' as ModuleTypeEnum,
        ELECTRONICWARFARE: 'ELECTRONIC_WARFARE' as ModuleTypeEnum,
        FTLPROPULSION: 'FTLPROPULSION' as ModuleTypeEnum,
        PROPULSION: 'PROPULSION' as ModuleTypeEnum,
        SHIELD: 'SHIELD' as ModuleTypeEnum,
        WEAPON: 'WEAPON' as ModuleTypeEnum
    };
}