/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Only to transfer enum values to the frontend.
 */
export interface EnumValueDto { 
    eDepositType?: Array<EnumValueDto.EDepositTypeEnum>;
    eResourceType?: Array<EnumValueDto.EResourceTypeEnum>;
    eEducationType?: Array<EnumValueDto.EEducationTypeEnum>;
    eCollectableType?: Array<EnumValueDto.ECollectableTypeEnum>;
    eCalculationType?: Array<EnumValueDto.ECalculationTypeEnum>;
    eAlignmentType?: Array<EnumValueDto.EAlignmentTypeEnum>;
    eHitArea?: Array<EnumValueDto.EHitAreaEnum>;
    eHullType?: Array<EnumValueDto.EHullTypeEnum>;
    eProductionCategory?: Array<EnumValueDto.EProductionCategoryEnum>;
    eRefinementSequence?: Array<EnumValueDto.ERefinementSequenceEnum>;
    eSupportType?: Array<EnumValueDto.ESupportTypeEnum>;
    eWarheadType?: Array<EnumValueDto.EWarheadTypeEnum>;
    eWeaponAlignment?: Array<EnumValueDto.EWeaponAlignmentEnum>;
    eWeaponType?: Array<EnumValueDto.EWeaponTypeEnum>;
}
export namespace EnumValueDto {
    export type EDepositTypeEnum = 'DEPOSITS' | 'DEMAND' | 'UTILIZATION' | 'COSTS' | 'INCOME' | 'CAPACITY';
    export const EDepositTypeEnum = {
        DEPOSITS: 'DEPOSITS' as EDepositTypeEnum,
        DEMAND: 'DEMAND' as EDepositTypeEnum,
        UTILIZATION: 'UTILIZATION' as EDepositTypeEnum,
        COSTS: 'COSTS' as EDepositTypeEnum,
        INCOME: 'INCOME' as EDepositTypeEnum,
        CAPACITY: 'CAPACITY' as EDepositTypeEnum
    };
    export type EResourceTypeEnum = 'CONSTRUCTION' | 'ORBITAL_CONSTRUCTION' | 'RESEARCH' | 'CREDITS' | 'METALORE' | 'RARE_ELEMENTS' | 'HEAVY_METALS' | 'POPULATION';
    export const EResourceTypeEnum = {
        CONSTRUCTION: 'CONSTRUCTION' as EResourceTypeEnum,
        ORBITALCONSTRUCTION: 'ORBITAL_CONSTRUCTION' as EResourceTypeEnum,
        RESEARCH: 'RESEARCH' as EResourceTypeEnum,
        CREDITS: 'CREDITS' as EResourceTypeEnum,
        METALORE: 'METALORE' as EResourceTypeEnum,
        RAREELEMENTS: 'RARE_ELEMENTS' as EResourceTypeEnum,
        HEAVYMETALS: 'HEAVY_METALS' as EResourceTypeEnum,
        POPULATION: 'POPULATION' as EResourceTypeEnum
    };
    export type EEducationTypeEnum = 'NONE' | 'SCHOOL' | 'COLLEGE' | 'UNIVERSITY' | 'ENLISTED' | 'OFFICER';
    export const EEducationTypeEnum = {
        NONE: 'NONE' as EEducationTypeEnum,
        SCHOOL: 'SCHOOL' as EEducationTypeEnum,
        COLLEGE: 'COLLEGE' as EEducationTypeEnum,
        UNIVERSITY: 'UNIVERSITY' as EEducationTypeEnum,
        ENLISTED: 'ENLISTED' as EEducationTypeEnum,
        OFFICER: 'OFFICER' as EEducationTypeEnum
    };
    export type ECollectableTypeEnum = 'COLLECTABLE' | 'FORFEITABLE' | 'VIABLE';
    export const ECollectableTypeEnum = {
        COLLECTABLE: 'COLLECTABLE' as ECollectableTypeEnum,
        FORFEITABLE: 'FORFEITABLE' as ECollectableTypeEnum,
        VIABLE: 'VIABLE' as ECollectableTypeEnum
    };
    export type ECalculationTypeEnum = 'NONE' | 'ADD' | 'SUBTRACT';
    export const ECalculationTypeEnum = {
        NONE: 'NONE' as ECalculationTypeEnum,
        ADD: 'ADD' as ECalculationTypeEnum,
        SUBTRACT: 'SUBTRACT' as ECalculationTypeEnum
    };
    export type EAlignmentTypeEnum = 'CHASE_ALIGNMENT' | 'BATTLE_ALIGNMENT';
    export const EAlignmentTypeEnum = {
        CHASEALIGNMENT: 'CHASE_ALIGNMENT' as EAlignmentTypeEnum,
        BATTLEALIGNMENT: 'BATTLE_ALIGNMENT' as EAlignmentTypeEnum
    };
    export type EHitAreaEnum = 'FITTING_AND_HULL' | 'ARMOR' | 'SIDEWALL' | 'PROPULSION' | 'ELOKA';
    export const EHitAreaEnum = {
        FITTINGANDHULL: 'FITTING_AND_HULL' as EHitAreaEnum,
        ARMOR: 'ARMOR' as EHitAreaEnum,
        SIDEWALL: 'SIDEWALL' as EHitAreaEnum,
        PROPULSION: 'PROPULSION' as EHitAreaEnum,
        ELOKA: 'ELOKA' as EHitAreaEnum
    };
    export type EHullTypeEnum = 'LAC' | 'VT' | 'FG' | 'DD' | 'CL' | 'CA' | 'BC' | 'BCP' | 'BB' | 'DN' | 'CLAC' | 'SD' | 'SDP' | 'AE' | 'AR' | 'FAT' | 'FR';
    export const EHullTypeEnum = {
        LAC: 'LAC' as EHullTypeEnum,
        VT: 'VT' as EHullTypeEnum,
        FG: 'FG' as EHullTypeEnum,
        DD: 'DD' as EHullTypeEnum,
        CL: 'CL' as EHullTypeEnum,
        CA: 'CA' as EHullTypeEnum,
        BC: 'BC' as EHullTypeEnum,
        BCP: 'BCP' as EHullTypeEnum,
        BB: 'BB' as EHullTypeEnum,
        DN: 'DN' as EHullTypeEnum,
        CLAC: 'CLAC' as EHullTypeEnum,
        SD: 'SD' as EHullTypeEnum,
        SDP: 'SDP' as EHullTypeEnum,
        AE: 'AE' as EHullTypeEnum,
        AR: 'AR' as EHullTypeEnum,
        FAT: 'FAT' as EHullTypeEnum,
        FR: 'FR' as EHullTypeEnum
    };
    export type EProductionCategoryEnum = 'PRODUCE' | 'CAPACITY' | 'REFINEMENT';
    export const EProductionCategoryEnum = {
        PRODUCE: 'PRODUCE' as EProductionCategoryEnum,
        CAPACITY: 'CAPACITY' as EProductionCategoryEnum,
        REFINEMENT: 'REFINEMENT' as EProductionCategoryEnum
    };
    export type ERefinementSequenceEnum = 'EDUCATION_CIVIL_I' | 'EDUCATION_CIVIL_II' | 'EDUCATION_CIVIL_III' | 'EDUCATION_MILITARY_I' | 'EDUCATION_MILITARY_II';
    export const ERefinementSequenceEnum = {
        CIVILI: 'EDUCATION_CIVIL_I' as ERefinementSequenceEnum,
        CIVILII: 'EDUCATION_CIVIL_II' as ERefinementSequenceEnum,
        CIVILIII: 'EDUCATION_CIVIL_III' as ERefinementSequenceEnum,
        MILITARYI: 'EDUCATION_MILITARY_I' as ERefinementSequenceEnum,
        MILITARYII: 'EDUCATION_MILITARY_II' as ERefinementSequenceEnum
    };
    export type ESupportTypeEnum = 'WEAPON' | 'ARMOR' | 'SIDEWALL' | 'PROPULSION' | 'FTLPROPULSION' | 'ELECTRONIC_WARFARE' | 'CREDITS' | 'METALORE' | 'RARE_ELEMENTS' | 'HEAVY_METALS' | 'POPULATION';
    export const ESupportTypeEnum = {
        WEAPON: 'WEAPON' as ESupportTypeEnum,
        ARMOR: 'ARMOR' as ESupportTypeEnum,
        SIDEWALL: 'SIDEWALL' as ESupportTypeEnum,
        PROPULSION: 'PROPULSION' as ESupportTypeEnum,
        FTLPROPULSION: 'FTLPROPULSION' as ESupportTypeEnum,
        ELECTRONICWARFARE: 'ELECTRONIC_WARFARE' as ESupportTypeEnum,
        CREDITS: 'CREDITS' as ESupportTypeEnum,
        METALORE: 'METALORE' as ESupportTypeEnum,
        RAREELEMENTS: 'RARE_ELEMENTS' as ESupportTypeEnum,
        HEAVYMETALS: 'HEAVY_METALS' as ESupportTypeEnum,
        POPULATION: 'POPULATION' as ESupportTypeEnum
    };
    export type EWarheadTypeEnum = 'LASER' | 'EXPLOSION' | 'KINETIC' | 'COUNTER_MISSILE';
    export const EWarheadTypeEnum = {
        LASER: 'LASER' as EWarheadTypeEnum,
        EXPLOSION: 'EXPLOSION' as EWarheadTypeEnum,
        KINETIC: 'KINETIC' as EWarheadTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as EWarheadTypeEnum
    };
    export type EWeaponAlignmentEnum = 'BOW' | 'STERN' | 'BROADSIDE';
    export const EWeaponAlignmentEnum = {
        BOW: 'BOW' as EWeaponAlignmentEnum,
        STERN: 'STERN' as EWeaponAlignmentEnum,
        BROADSIDE: 'BROADSIDE' as EWeaponAlignmentEnum
    };
    export type EWeaponTypeEnum = 'MISSILE' | 'BEAM' | 'COUNTER_MISSILE' | 'POINT_DEFENSE';
    export const EWeaponTypeEnum = {
        MISSILE: 'MISSILE' as EWeaponTypeEnum,
        BEAM: 'BEAM' as EWeaponTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as EWeaponTypeEnum,
        POINTDEFENSE: 'POINT_DEFENSE' as EWeaponTypeEnum
    };
}