/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface EShipClassType { 
    /**
     * The type name of this  transformed enum.
     */
    typeName: string;
    /**
     * The icon name for this resource.
     */
    iconName: string;
    /**
     * The folder name for resources.
     */
    folder: string;
    /**
     * The hulls type.
     */
    type: string;
    /**
     * If the hull is a pod layer.
     */
    podLayer: boolean;
    /**
     * If the hull is an auxiliary ship.
     */
    auxiliaryShip: boolean;
    /**
     * The hulls description.
     */
    description: string;
}