/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {FleetOrbit} from "./fleetOrbit"; /**
 * .
 */
export interface FleetSplit { 
    /**
     * The first are the fleet names. Warship IDs to Fleet name.
     */
    fleetConstellations: { [key: string]: Array<number>; };
    orbit:FleetOrbit;
}
