/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface FleetMovement { 
    /**
     * The transferred resources.
     */
    fleetName: string;
    /**
     * The origin planet's name.
     */
    fromPlanet: string;
    /**
     * The origin systems's name.
     */
    fromSystem: string;
    /**
     * The designation planet's name.
     */
    toPlanet: string;
    /**
     * The designation system's name.
     */
    toSystem: string;
    /**
     * The duration of the journey.
     */
    duration: number;
}