/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Orbit } from './orbit';
import { Planet } from './planet';
import { StarSystem } from './starSystem';

/**
 * .
 */
export interface FleetOrbit { 
    planet?: Planet;
    system?: StarSystem;
    orbit?: Orbit;
}