/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface FleetMovement { 
    /**
     * The fleets name.
     */
    fleetName: string;
    /**
     * The fleet owners name.
     */
    fleetOwnerName: string;
    /**
     * The origin planet's name.
     */
    originPlanet?: string;
    /**
     * The origin systems's name.
     */
    originSystem: string;
    /**
     * The designation planet's name.
     */
    destinationPlanet?: string;
    /**
     * The designation planet owners name.
     */
    destinationPlanetOwner?: string;
    /**
     * The designation system's name.
     */
    destinationSystem: string;
    /**
     * The duration of the journey.
     */
    duration: number;
    /**
     * If the incoming fleet is from a foreign empire.
     */
    isForeignFleet: boolean;
}