/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The entry of a forum's thread.
 */
export interface ForumMessage { 
    /**
     * The id of the message.
     */
    idForumMessage: number;
    /**
     * The id of the message's parent thread.
     */
    idForumThread: number;
    /**
     * The id of the forum.
     */
    idForum: number;
    /**
     * The id of the author.
     */
    idAuthor: number;
    /**
     * The username of the author.
     */
    author: string;
    /**
     * The message itself.
     */
    message: string;
    /**
     * The creation timestamp.
     */
    sentAt: Date;
}
