/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ForumMessage } from './forumMessage';

/**
 * The entry of a forum's thread.
 */
export interface ForumMessageContainer { 
    /**
     * The page of the message.
     */
    page: number;
    /**
     * The messages.
     */
    messages: Array<ForumMessage>;
}