/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Player } from './player';

/**
 * The entry of a forum's thread.
 */
export interface ForumMessage { 
    /**
     * The id of the message.
     */
    idForumMessage: number;
    /**
     * The id of the message's parent thread.
     */
    idForumThread: number;
    /**
     * The id of the forum.
     */
    idForum: number;
    author: Player;
    /**
     * The user's profile pic.
     */
    profilePic: string;
    /**
     * The message itself.
     */
    message: string;
    /**
     * The creation timestamp.
     */
    sentAt: Date;
}