/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HasNamedTechLevel } from './hasNamedTechLevel';

/**
 * .
 */
export interface HasCostsByParent { 
    hasNamedTechLevel: HasNamedTechLevel;
    /**
     * The percentage of the parent's module cost which represents the costs of 'this'.
     */
    costsPercentage: number;
}