/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface HasNamedTechLevel { 
    /**
     * The name of this module.
     */
    name: string;
    /**
     * The technical type name of this module.
     */
    technicalTypeName: string;
    /**
     * The description of this module.
     */
    description: string;
    /**
     * The level of this module.
     */
    techLevel: HasNamedTechLevel.TechLevelEnum;
}
export namespace HasNamedTechLevel {
    export type TechLevelEnum = 'TECH_I' | 'TECH_II' | 'TECH_III';
    export const TechLevelEnum = {
        I: 'TECH_I' as TechLevelEnum,
        II: 'TECH_II' as TechLevelEnum,
        III: 'TECH_III' as TechLevelEnum
    };
}
