/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EHullType } from './eHullType';

export interface Hull { 
    /**
     * The unaligned construction capacity.
     */
    constructionCapacity: number;
    /**
     * The bow-aligned construction capacity.
     */
    constructionCapacityBow: number;
    /**
     * The broadside-aligned construction capacity.
     */
    constructionCapacityBroadsides: number;
    /**
     * The stern-aligned construction capacity.
     */
    constructionCapacityStern: number;
    /**
     * The description of the hull.
     */
    description: string;
    hullType: EHullType;
    /**
     * The id of this hull.
     */
    idHull: number;
    /**
     * The name of this hull.
     */
    name: string;
    /**
     * The overall construction capacity as displacement like in the wet navies.
     */
    overallConstructionCapacity: number;
}