/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Hull { 
    /**
     * The unaligned construction capacity.
     */
    constructionCapacity: number;
    /**
     * The bow-aligned construction capacity.
     */
    constructionCapacityBow: number;
    /**
     * The broadside-aligned construction capacity.
     */
    constructionCapacityBroadsides: number;
    /**
     * The stern-aligned construction capacity.
     */
    constructionCapacityStern: number;
    /**
     * The description of the hull.
     */
    description: string;
    /**
     * The hull type.
     */
    hullType: Hull.HullTypeEnum;
    /**
     * The level represents the size of a ship, bigger levels represents bigger hulls.
     */
    level: number;
    /**
     * The name of this hull.
     */
    name: string;
}
export namespace Hull {
    export type HullTypeEnum = 'AE' | 'AR' | 'BB' | 'BC' | 'BCP' | 'CA' | 'CC' | 'CL' | 'CLAC' | 'DD' | 'DN' | 'FAT' | 'FG' | 'FR' | 'LAC' | 'SD' | 'SDP';
    export const HullTypeEnum = {
        AE: 'AE' as HullTypeEnum,
        AR: 'AR' as HullTypeEnum,
        BB: 'BB' as HullTypeEnum,
        BC: 'BC' as HullTypeEnum,
        BCP: 'BCP' as HullTypeEnum,
        CA: 'CA' as HullTypeEnum,
        CC: 'CC' as HullTypeEnum,
        CL: 'CL' as HullTypeEnum,
        CLAC: 'CLAC' as HullTypeEnum,
        DD: 'DD' as HullTypeEnum,
        DN: 'DN' as HullTypeEnum,
        FAT: 'FAT' as HullTypeEnum,
        FG: 'FG' as HullTypeEnum,
        FR: 'FR' as HullTypeEnum,
        LAC: 'LAC' as HullTypeEnum,
        SD: 'SD' as HullTypeEnum,
        SDP: 'SDP' as HullTypeEnum
    };
}