/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Building } from './building';
import { Construction } from './construction';
import { UserJson } from './userJson';

export interface Job { 
    /**
     * The targeted amount of ships in case of an shipyard job..
     */
    amountShips?: number;
    buildingTarget?: Building;
    facility: Construction;
    /**
     * Is this a building job build.
     */
    isBuildingJob: boolean;
    /**
     * Is this a research job.
     */
    isResearchJob: boolean;
    /**
     * Is this a shipyard job.
     */
    isShipyardJob: boolean;
    /**
     * If this if a research job.
     */
    researchTarget?: string;
    /**
     * The type of costs.
     */
    resourceType: Job.ResourceTypeEnum;
    /**
     * If this if a shipyard job.
     */
    shipYardTarget?: string;
    /**
     * The targeted level if it is a research or building.
     */
    targetLevel?: number;
    /**
     * The left duration of this job.
     */
    ticksLeft: number;
    user: UserJson;
}
export namespace Job {
    export type ResourceTypeEnum = 'CONSTRUCTION' | 'CREDITS' | 'HEAVY_METALS' | 'METALORE' | 'ORBITAL_CONSTRUCTION' | 'POPULATION' | 'RARE_ELEMENTS' | 'RESEARCH';
    export const ResourceTypeEnum = {
        CONSTRUCTION: 'CONSTRUCTION' as ResourceTypeEnum,
        CREDITS: 'CREDITS' as ResourceTypeEnum,
        HEAVYMETALS: 'HEAVY_METALS' as ResourceTypeEnum,
        METALORE: 'METALORE' as ResourceTypeEnum,
        ORBITALCONSTRUCTION: 'ORBITAL_CONSTRUCTION' as ResourceTypeEnum,
        POPULATION: 'POPULATION' as ResourceTypeEnum,
        RAREELEMENTS: 'RARE_ELEMENTS' as ResourceTypeEnum,
        RESEARCH: 'RESEARCH' as ResourceTypeEnum
    };
}