/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface JWT { 
    /**
     * The access token to authenticate every request against the backend.
     */
    accessToken: string;
    /**
     * The access token to authenticate every request against the backend.
     */
    refreshToken: string;
    /**
     * The user's name.
     */
    username: string;
    /**
     * The user's ID.
     */
    idUser: number;
    /**
     * The id of the user's alliance.
     */
    idAlliance?: number;
    /**
     * The user's role.
     */
    role: JWT.RoleEnum;
    /**
     * The user's in-game roles.
     */
    gameUserRoles: Array<JWT.GameUserRolesEnum>;
}
export namespace JWT {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
    export type GameUserRolesEnum = 'ALLIANCE_ADMIN';
    export const GameUserRolesEnum = {
        ALLIANCE_ADMIN: 'ALLIANCE_ADMIN' as GameUserRolesEnum
    };
}
