/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseModule } from './baseModule';
import { Missile } from './missile';

/**
 * .
 */
export interface Launcher { 
    baseModule: BaseModule;
    /**
     * The way how the damage will be projected.
     */
    weaponType: Launcher.WeaponTypeEnum;
    /**
     * The bunch of allowed missiles for this launcher.
     */
    allowedMissiles: Array<Missile>;
}
export namespace Launcher {
    export type WeaponTypeEnum = 'MISSILE' | 'BEAM' | 'COUNTER_MISSILE' | 'POINT_DEFENSE';
    export const WeaponTypeEnum = {
        MISSILE: 'MISSILE' as WeaponTypeEnum,
        BEAM: 'BEAM' as WeaponTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as WeaponTypeEnum,
        POINTDEFENSE: 'POINT_DEFENSE' as WeaponTypeEnum
    };
}