/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AmmunitionModule } from './ammunitionModule';
import { BaseModule } from './baseModule';
import { Missile } from './missile';

/**
 * .
 */
export interface Launcher { 
    baseModule: BaseModule;
    /**
     * The way how the damage will be projected.
     */
    weaponType: Launcher.WeaponTypeEnum;
    /**
     * The possible mount points of this weapon.
     */
    alignmentTypes: Array<Launcher.AlignmentTypesEnum>;
    /**
     * The bunch of allowed missiles for this launcher.
     */
    allowedMissiles: Array<Missile>;
    ammunitionModule: AmmunitionModule;
}
export namespace Launcher {
    export type WeaponTypeEnum = 'MISSILE' | 'BEAM' | 'COUNTER_MISSILE' | 'POINT_DEFENSE';
    export const WeaponTypeEnum = {
        MISSILE: 'MISSILE' as WeaponTypeEnum,
        BEAM: 'BEAM' as WeaponTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as WeaponTypeEnum,
        POINTDEFENSE: 'POINT_DEFENSE' as WeaponTypeEnum
    };
    export type AlignmentTypesEnum = 'BOW' | 'STERN' | 'BROADSIDE';
    export const AlignmentTypesEnum = {
        BOW: 'BOW' as AlignmentTypesEnum,
        STERN: 'STERN' as AlignmentTypesEnum,
        BROADSIDE: 'BROADSIDE' as AlignmentTypesEnum
    };
}