/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractId } from './abstractId';
import { UserJson } from './userJson';

/**
 * .
 */
export interface LossRole { 
    owner: UserJson;
    fleet: AbstractId;
    /**
     * The name of the war ship which was destroyed.
     */
    warShipName: string;
    warship: AbstractId;
    shipClass: AbstractId;
}
