/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShipClass } from './shipClass';
import { UserJson } from './userJson';

export interface LossRole { 
    owner: UserJson;
    shipClass: ShipClass;
    /**
     * The name of the war ship which was destroyed.
     */
    warShipName: string;
}