/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractId } from './abstractId';
import { Orbit } from './orbit';

/**
 * .
 */
export interface ManeuverElement { 
    maneuver: AbstractId;
    p1: Orbit;
    cp1: Orbit;
    cp2: Orbit;
    p2: Orbit;
    /**
     * Represented as percent value.
     */
    partOfManeuver: number;
    /**
     * The number of planned execution as part of the parent maneuver.
     */
    sequenceNo: number;
}