/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CombatRoundKey } from './combatRoundKey';
import { Fleet } from './fleet';
import { Orbit } from './orbit';

export interface MissileMovement { 
    actor: Fleet;
    combatRoundKey: CombatRoundKey;
    lastPosition: Orbit;
    /**
     * The amount of missiles in this salvo.
     */
    missileAmount: number;
    /**
     * The UUID of the moving missile salvo.
     */
    movingMissileSalvo: string;
    position: Orbit;
    /**
     * The amount of rounds which have to be passed before in range for a hit.
     */
    roundsToTravel: number;
    target: Fleet;
    targetPosition: Orbit;
}