/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractId } from './abstractId';
import { CombatRoundKey } from './combatRoundKey';
import { Distance } from './distance';

/**
 * .
 */
export interface MissileMovement {
    combatRoundKey: CombatRoundKey;
    actor: AbstractId;
    actorOwner: AbstractId;
    target: AbstractId;
    /**
     * The UUID of the moving missile salvo.
     */
    movingMissileSalvo: string;
    /**
     * The amount of missiles in this salvo.
     */
    missileAmount: number;
    lengthOnTrack: Distance;
}
