/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MissileMotor } from './missileMotor';
import { Warhead } from './warhead';

export interface Missile { 
    /**
     * The engine capacity of this missile.
     */
    elokaResistance: number;
    /**
     * The id of this Missile.
     */
    idMissile: number;
    /**
     * The implemented engine of this missile.
     */
    missileMotors: Array<MissileMotor>;
    /**
     * The engine capacity of this missile.
     */
    motorCapacity: number;
    /**
     * The type name of this missile.
     */
    typeName: string;
    warhead: Warhead;
    /**
     * The warhead capacity of this missile.
     */
    warheadCapacity: number;
}
