/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseModule } from './baseModule';
import { Mass } from './mass';
import { MissileMotor } from './missileMotor';
import { ResourceDeposit } from './resourceDeposit';
import { Warhead } from './warhead';

/**
 * .
 */
export interface Missile { 
    costs?: ResourceDeposit;
    baseModule: BaseModule;
    /**
     * The engine capacity of this missile.
     */
    elokaResistance: number;
    tonnage: Mass;
    warhead: Warhead;
    missileMotor: MissileMotor;
}