/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Acceleration } from './acceleration';
import { Time } from './time';

/**
 * .
 */
export interface MissileMotor { 
    endurance: Time;
    acceleration: Acceleration;
    /**
     * Defines the capability of this weapon to penetrate the shield.  The means the maneuver capability to find a gap in the tank to fire into it, for instance.
     */
    maneuverability: number;
    /**
     * The capacity usage of this module.
     */
    useCapacity: number;
}