/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Planet } from './planet';
import { WarShip } from './warShip';

/**
 * .
 */
export interface Mission { 
    /**
     * The mission.
     */
    idMission?: number;
    /**
     * The type of the mission.
     */
    missionType: Mission.MissionTypeEnum;
    venue: Planet;
    /**
     * The mission's individual war ships.
     */
    ships: Array<WarShip>;
}
export namespace Mission {
    export type MissionTypeEnum = 'PIRATE_RAID' | 'PIRATE_HUNT' | 'CONVOY_PROTECTION';
    export const MissionTypeEnum = {
        PIRATE_RAID: 'PIRATE_RAID' as MissionTypeEnum,
        PIRATE_HUNT: 'PIRATE_HUNT' as MissionTypeEnum,
        CONVOY_PROTECTION: 'CONVOY_PROTECTION' as MissionTypeEnum
    };
}
