/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FleetOrbit } from './fleetOrbit';

export interface Move { 
    /**
     * The fleet which is in motion.
     */
    idFleetInMotion: number;
    /**
     * The current left over duration of this movement.
     */
    moveDoneAtZero: number;
    /**
     * The original duration of this movement.
     */
    originalDuration: number;
    startOrbit: FleetOrbit;
    targetOrbit: FleetOrbit;
}
