/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FleetOrbit } from './fleetOrbit';
import { FlightPlan } from './flightPlan';
import { Tick } from './tick';

/**
 * .
 */
export interface Move { 
    /**
     * The fleet which is in motion.
     */
    idFleetInMotion: number;
    startOrbit: FleetOrbit;
    targetOrbit: FleetOrbit;
    started: Tick;
    /**
     * The current left over duration of this movement.
     */
    ticksLeft: number;
    /**
     * The original duration of this movement.
     */
    originalDuration: number;
    /**
     * The waypoints of this move.
     */
    waypoints: Array<FleetOrbit>;
    /**
     * The real flight plan of this move.
     */
    flightPlan: Array<FlightPlan>;
}