/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FleetOrbit } from './fleetOrbit';

/**
 * .
 */
export interface Move { 
    /**
     * The fleet which is in motion.
     */
    idFleetInMotion: number;
    startOrbit: FleetOrbit;
    targetOrbit: FleetOrbit;
    /**
     * The current left over duration of this movement.
     */
    moveDoneAtZero: number;
    /**
     * The original duration of this movement.
     */
    originalDuration: number;
}