/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseModule } from './baseModule';

export interface PassiveModule { 
    baseModule: BaseModule;
    /**
     * If the support is increasing or decreasing.
     */
    calculationType: PassiveModule.CalculationTypeEnum;
    /**
     * What type of property is supported.
     */
    supportType: PassiveModule.SupportTypeEnum;
}
export namespace PassiveModule {
    export type CalculationTypeEnum = 'ADD' | 'SUBTRACT';
    export const CalculationTypeEnum = {
        ADD: 'ADD' as CalculationTypeEnum,
        SUBTRACT: 'SUBTRACT' as CalculationTypeEnum
    };
    export type SupportTypeEnum = 'ARMOR' | 'CREDITS' | 'ELECTRONIC_WARFARE' | 'FTLPROPULSION' | 'HEAVY_METALS' | 'METALORE' | 'POPULATION' | 'PROPULSION' | 'RARE_ELEMENTS' | 'SHIELD' | 'WEAPON';
    export const SupportTypeEnum = {
        ARMOR: 'ARMOR' as SupportTypeEnum,
        CREDITS: 'CREDITS' as SupportTypeEnum,
        ELECTRONICWARFARE: 'ELECTRONIC_WARFARE' as SupportTypeEnum,
        FTLPROPULSION: 'FTLPROPULSION' as SupportTypeEnum,
        HEAVYMETALS: 'HEAVY_METALS' as SupportTypeEnum,
        METALORE: 'METALORE' as SupportTypeEnum,
        POPULATION: 'POPULATION' as SupportTypeEnum,
        PROPULSION: 'PROPULSION' as SupportTypeEnum,
        RAREELEMENTS: 'RARE_ELEMENTS' as SupportTypeEnum,
        SHIELD: 'SHIELD' as SupportTypeEnum,
        WEAPON: 'WEAPON' as SupportTypeEnum
    };
}
