/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PirateRaidActionItem } from './pirateRaidActionItem';
import { Planet } from './planet';

/**
 * .
 */
export interface PirateRaidActionItemGroup { 
    /**
     * What happens.
     */
    missionType: PirateRaidActionItemGroup.MissionTypeEnum;
    venue: Planet;
    /**
     * The actions to report.
     */
    actionItems: Array<PirateRaidActionItem>;
}
export namespace PirateRaidActionItemGroup {
    export type MissionTypeEnum = 'PIRATE_RAID' | 'PIRATE_HUNT' | 'CONVOY_PROTECTION' | 'CONVOY_RAID';
    export const MissionTypeEnum = {
        PIRATE_RAID: 'PIRATE_RAID' as MissionTypeEnum,
        PIRATE_HUNT: 'PIRATE_HUNT' as MissionTypeEnum,
        CONVOY_PROTECTION: 'CONVOY_PROTECTION' as MissionTypeEnum,
        CONVOY_RAID: 'CONVOY_RAID' as MissionTypeEnum
    };
}