/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Orbit } from './orbit';
import { StarSystem } from './starSystem';
import { UserJson } from './userJson';

export interface Planet { 
    /**
     * The timestamp when this planet was colonized first.
     */
    colonizedAt?: Date;
    /**
     * The ID of this planet.
     */
    idPlanet: number;
    /**
     * The name of this planet.
     */
    name: string;
    orbit: Orbit;
    owner?: UserJson;
    /**
     * The planet's class.
     */
    planetType: Planet.PlanetTypeEnum;
    system: StarSystem;
}
export namespace Planet {
    export type PlanetTypeEnum = 'PLANET';
    export const PlanetTypeEnum = {
        PLANET: 'PLANET' as PlanetTypeEnum
    };
}