/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EPlanetClassType } from './ePlanetClassType';
import { Orbit } from './orbit';
import { UserJson } from './userJson';

/**
 * .
 */
export interface Planet { 
    /**
     * The ID of this planet.
     */
    idPlanet: number;
    owner?: UserJson;
    /**
     * If this planet is the main planet of the owner.
     */
    isMain: boolean;
    /**
     * The name of this planet.
     */
    name: string;
    /**
     * The star system ID which this planet is part of.
     */
    idStarSystem: number;
    orbit: Orbit;
    /**
     * The timestamp when this planet was colonized first.
     */
    colonizedAt?: Date;
    planetType: EPlanetClassType;
}
