/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Acceleration } from './acceleration';
import { Time } from './time';
import { Velocity } from './velocity';

/**
 * .
 */
export interface PropulsionCapacity { 
    acceleration: Acceleration;
    velocity: Velocity;
    timeToVMax: Time;
    /**
     * The time metric.
     */
    timeMetric: PropulsionCapacity.TimeMetricEnum;
}
export namespace PropulsionCapacity {
    export type TimeMetricEnum = 'SECOND' | 'MINUTE' | 'HOUR' | 'DAY' | 'WEEK' | 'MONTH' | 'YEAR';
    export const TimeMetricEnum = {
        SECOND: 'SECOND' as TimeMetricEnum,
        MINUTE: 'MINUTE' as TimeMetricEnum,
        HOUR: 'HOUR' as TimeMetricEnum,
        DAY: 'DAY' as TimeMetricEnum,
        WEEK: 'WEEK' as TimeMetricEnum,
        MONTH: 'MONTH' as TimeMetricEnum,
        YEAR: 'YEAR' as TimeMetricEnum
    };
}