/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface Propulsion { 
    /**
     * The id of this module.
     */
    idModule: number;
    /**
     * The name of this module.
     */
    name: string;
    /**
    * The technical type name of this module.
    */
    technicalTypeName:string;
    /**
     * The description of this module.
     */
    description: string;
    /**
     * The percentage of the parent's module cost which represents the costs of 'this'.
     */
    costsPercentage: number;
    /**
     * The base effect value of this module.
     */
    effectValue: number;
    /**
     * The level of this module.
     */
    techLevel: Propulsion.TechLevelEnum;
    /**
     * If this propulsion module if for faster then light.
     */
    hyperBand: Propulsion.HyperBandEnum;
    /**
     * If this propulsion module is for military or civil purposes.
     */
    technologyType: Propulsion.TechnologyTypeEnum;
}
export namespace Propulsion {
    export type TechLevelEnum = 'TECH_I' | 'TECH_II' | 'TECH_III';
    export const TechLevelEnum = {
        I: 'TECH_I' as TechLevelEnum,
        II: 'TECH_II' as TechLevelEnum,
        III: 'TECH_III' as TechLevelEnum
    };
    export type HyperBandEnum = 'NONE' | 'ALPHA' | 'BETA' | 'GAMMA' | 'DELTA' | 'EPSILON' | 'ZETA' | 'ETA' | 'THETA';
    export const HyperBandEnum = {
        NONE: 'NONE' as HyperBandEnum,
        ALPHA: 'ALPHA' as HyperBandEnum,
        BETA: 'BETA' as HyperBandEnum,
        GAMMA: 'GAMMA' as HyperBandEnum,
        DELTA: 'DELTA' as HyperBandEnum,
        EPSILON: 'EPSILON' as HyperBandEnum,
        ZETA: 'ZETA' as HyperBandEnum,
        ETA: 'ETA' as HyperBandEnum,
        THETA: 'THETA' as HyperBandEnum
    };
    export type TechnologyTypeEnum = 'CIVIL' | 'MILITARY';
    export const TechnologyTypeEnum = {
        CIVIL: 'CIVIL' as TechnologyTypeEnum,
        MILITARY: 'MILITARY' as TechnologyTypeEnum
    };
}
