/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CombatRoundKey } from './combatRoundKey';
import { Distance } from './distance';
import { Fleet } from './fleet';

export interface ReleasedVolley { 
    actor: Fleet;
    /**
     * The amount of missiles in this salvo.
     */
    amountOfShots: number;
    combatRoundKey: CombatRoundKey;
    /**
     * The UUID of the damage dealer.
     */
    damageDealer: string;
    initialDistance: Distance;
    target: Fleet;
    /**
     * The type of the damage dealer.
     */
    weaponType: ReleasedVolley.WeaponTypeEnum;
}
export namespace ReleasedVolley {
    export type WeaponTypeEnum = 'BEAM' | 'COUNTER_MISSILE' | 'MISSILE' | 'POINT_DEFENSE';
    export const WeaponTypeEnum = {
        BEAM: 'BEAM' as WeaponTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as WeaponTypeEnum,
        MISSILE: 'MISSILE' as WeaponTypeEnum,
        POINTDEFENSE: 'POINT_DEFENSE' as WeaponTypeEnum
    };
}
