/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface Research { 
    /**
     * The id of this research.
     */
    idResearch: number;
    /**
     * The name of this research.
     */
    name: string;
    /**
     * The description of this research.
     */
    description: string;
    /**
     * The maximum level of this research.
     */
    levelCap: number;
}