/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EResourceType } from './eResourceType';

/**
 * .
 */
export interface ResourceAmount { 
    resourceType: EResourceType;
    /**
     * The amount for the resource.
     */
    amount: number;
}