/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RPGTextBlocks } from './rPGTextBlocks';

/**
 * .
 */
export interface RolePlayData { 
    title?: string;
    titleAbbreviation?: string;
    firstname?: string;
    surname?: string;
    /**
     * The user's selected ship names.
     */
    shipPrefix?: string;
    /**
     * The empire's name.
     */
    empireName?: string;
    /**
     * The user's selected ship name templates.
     */
    shipNameTemplates: Array<RolePlayData.ShipNameTemplatesEnum>;
    /**
     * The user's selected ship names.
     */
    shipNames: Array<string>;
    textBlocks: RPGTextBlocks;
}
export namespace RolePlayData {
    export type ShipNameTemplatesEnum = 'MANTICORE' | 'HAVEN' | 'ANDERMAN' | 'SILESIA' | 'SOLARIAN_LEAGUE';
    export const ShipNameTemplatesEnum = {
        MANTICORE: 'MANTICORE' as ShipNameTemplatesEnum,
        HAVEN: 'HAVEN' as ShipNameTemplatesEnum,
        ANDERMAN: 'ANDERMAN' as ShipNameTemplatesEnum,
        SILESIA: 'SILESIA' as ShipNameTemplatesEnum,
        SOLARIAN_LEAGUE: 'SOLARIAN_LEAGUE' as ShipNameTemplatesEnum
    };
}