/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlignedFitting } from './alignedFitting';
import { AmmunitionFitting } from './ammunitionFitting';
import { Armor } from './armor';
import { ElectronicWarfare } from './electronicWarfare';
import { Hull } from './hull';
import { Propulsion } from './propulsion';
import { Sidewall } from './sidewall';
import { SupportFitting } from './supportFitting';
import { UserJson } from './userJson';

/**
 * .
 */
export interface ShipClass { 
    /**
     * The ID.
     */
    idShipClass?: number;
    owner: UserJson;
    /**
     * The name of this class.
     */
    name: string;
    hull: Hull;
    propulsion?: Propulsion;
    armor?: Armor;
    sidewall?: Sidewall;
    electronicWarfare?: ElectronicWarfare;
    /**
     * The weapon systems of this class.
     */
    fittings: Array<AlignedFitting>;
    /**
     * The ammunition loadout of this class.
     */
    ammunitionFittings: Array<AmmunitionFitting>;
    /**
     * The support fitting of this class.
     */
    supportFittings: Array<SupportFitting>;
    /**
     * The id of the predecessor of this class.
     */
    idPredecessor?: number;
    /**
     * The id of the successor of this class.
     */
    idSuccessor?: number;
    /**
     * The mark of this class.
     */
    mark: number;
}
