/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CombatRoundKey } from './combatRoundKey';
import { Distance } from './distance';
import { Fleet } from './fleet';
import { HitLog } from './hitLog';
import { LossRole } from './lossRole';

export interface ShipKillerHit { 
    actor: Fleet;
    combatRoundKey: CombatRoundKey;
    /**
     * The UUID of the damage dealer.
     */
    damageDealer: string;
    distance: Distance;
    /**
     * A hit log list.
     */
    hitLogs: Array<HitLog>;
    /**
     * If the hit results in a destroyed ship, this will be logged here. By the id of the hit log.
     */
    lossesByHit: { [key: string]: LossRole; };
    /**
     * The result of this salvo.
     */
    result: ShipKillerHit.ResultEnum;
    target: Fleet;
}
export namespace ShipKillerHit {
    export type ResultEnum = 'BURST_ON_IMPELLER_WEDGE' | 'DAMAGE_APPLIED';
    export const ResultEnum = {
        BURSTONIMPELLERWEDGE: 'BURST_ON_IMPELLER_WEDGE' as ResultEnum,
        DAMAGEAPPLIED: 'DAMAGE_APPLIED' as ResultEnum
    };
}
