/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CapabilityValue } from './capabilityValue';

/**
 * .
 */
export interface SpacecraftCapabilities { 
    /**
     * The effect values per module type.
     */
    capabilities: Array<CapabilityValue>;
}