/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EStarClassType } from './eStarClassType';
import { Orbit } from './orbit';
import { Planet } from './planet';

/**
 * .
 */
export interface StarSystem { 
    /**
     * The ID of this star system.
     */
    idStarSystem: number;
    /**
     * The name of this star system.
     */
    name: string;
    orbit: Orbit;
    starClassType: EStarClassType;
    /**
     * The bunch of planets as part of the system.
     */
    planets: Array<Planet>;
}