/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Colonization } from './colonization';
import { Distance } from './distance';
import { ResourceDeposit } from './resourceDeposit';
import { StarSystem } from './starSystem';

/**
 * .
 */
export interface StarSystemColonization { 
    starSystem: StarSystem;
    /**
     * The star system with its distance to all known systems by id.
     */
    distanceMap: { [key: string]: Distance; };
    /**
     * The costs to buy the colonization information about the system.
     */
    costsToBuyColonizationInformation: string;
    /**
     * The costs to colonize the planet by idPlanet.
     */
    costsToColonization: { [key: string]: ResourceDeposit; };
    /**
     * The costs to colonize the planet by idPlanet.
     */
    colonizationsByPlanet: { [key: string]: Colonization; };
}