/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Contains the several states which can be taken from a spacecraft.
 */
export interface StateBlock { 
    /**
     * If the spacecraft is marked as wrecked.
     */
    isDeleted: boolean;
    /**
     * If the spacecraft is marked as active.
     */
    isOperational: boolean;
    /**
     * If the spacecraft can do actions.
     */
    isActive: boolean;
    /**
     * If the spacecraft is able to fight.
     */
    isFightingCapable: boolean;
    /**
     * If the spacecraft needs a repair.
     */
    needsRepair: boolean;
}