/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Building } from './building';
import { EShipClassType } from './eShipClassType';
import { Research } from './research';

/**
 * .
 */
export interface TickAdvice { 
    /**
     * If ground constructions are possible.
     */
    constructionPossible: boolean;
    /**
     * If shipyard jobs are possible.
     */
    shipyardPossible: boolean;
    /**
     * If a research is possible.
     */
    researchPossible: boolean;
    suggestedBuilding?: Building;
    suggestedResearch?: Research;
    suggestedShipClass?: EShipClassType;
    /**
     * The suggested class to build up.
     */
    suggestedMission?: TickAdvice.SuggestedMissionEnum;
}
export namespace TickAdvice {
    export type SuggestedMissionEnum = 'PIRATE_RAID' | 'PIRATE_HUNT' | 'CONVOY_PROTECTION' | 'CONVOY_RAID';
    export const SuggestedMissionEnum = {
        PIRATE_RAID: 'PIRATE_RAID' as SuggestedMissionEnum,
        PIRATE_HUNT: 'PIRATE_HUNT' as SuggestedMissionEnum,
        CONVOY_PROTECTION: 'CONVOY_PROTECTION' as SuggestedMissionEnum,
        CONVOY_RAID: 'CONVOY_RAID' as SuggestedMissionEnum
    };
}