/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The time to reach the maximum velocity.
 */
export interface Time { 
    /**
     * The value of this distance.
     */
    coordinate: number;
    /**
     * The metric of this time.
     */
    timeMetric: Time.TimeMetricEnum;
}
export namespace Time {
    export type TimeMetricEnum = 'SECOND' | 'MINUTE' | 'HOUR' | 'DAY' | 'WEEK' | 'MONTH' | 'YEAR';
    export const TimeMetricEnum = {
        SECOND: 'SECOND' as TimeMetricEnum,
        MINUTE: 'MINUTE' as TimeMetricEnum,
        HOUR: 'HOUR' as TimeMetricEnum,
        DAY: 'DAY' as TimeMetricEnum,
        WEEK: 'WEEK' as TimeMetricEnum,
        MONTH: 'MONTH' as TimeMetricEnum,
        YEAR: 'YEAR' as TimeMetricEnum
    };
}