/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractId } from './abstractId';
import { ConvoyRaidActionItem } from './convoyRaidActionItem';
import { TradeOffer } from './tradeOffer';

/**
 * .
 */
export interface TradeContract { 
    /**
     * The database id.
     */
    idTradedResource: number;
    /**
     * If the contract has finished.
     */
    isFinished: boolean;
    offer: TradeOffer;
    buyer: AbstractId;
    destination: AbstractId;
    /**
     * The actions to report.
     */
    actionItems: Array<ConvoyRaidActionItem>;
}