/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tick } from './tick';
import { Trade } from './trade';

/**
 * .
 */
export interface TradesByTick { 
    tick: Tick;
    /**
     * The trades.
     */
    trades: Array<Trade>;
    /**
     * The sales.
     */
    sales: Array<Trade>;
    /**
     * The purchases.
     */
    purchases: Array<Trade>;
}