/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HumanResourceAmount } from './humanResourceAmount';
import { Planet } from './planet';
import { ResourceAmount } from './resourceAmount';

/**
 * .
 */
export interface TransportJob { 
    from: Planet;
    to: Planet;
    /**
     * The transferred resources.
     */
    resources: Array<ResourceAmount>;
    /**
     * The transferred humans.
     */
    humanResources: Array<HumanResourceAmount>;
}
