/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractId } from './abstractId';
import { HumanResourceAmount } from './humanResourceAmount';
import { ResourceAmount } from './resourceAmount';
import { WarShip } from './warShip';

/**
 * .
 */
export interface TransportJob { 
    from: AbstractId;
    to: AbstractId;
    /**
     * The transferred resources.
     */
    resources: Array<ResourceAmount>;
    /**
     * The transferred humans.
     */
    humanResources: Array<HumanResourceAmount>;
    /**
     * If ships were moved.
     */
    ships: Array<WarShip>;
}