/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface Translation { 
    /**
     * The id of the translation where this dto belongs to.
     */
    idTranslatable: number;
    /**
     * For what kind of item the translation is for.
     */
    translationTarget?: Translation.TranslationTargetEnum;
    /**
     * Which kind of test will be translated by this item.
     */
    translatableType?: Translation.TranslatableTypeEnum;
    /**
     * The database id of the parent item.
     */
    idParent?: number;
    /**
     * The language code of this localization.
     */
    languageCode: string;
    /**
     * The localized string.
     */
    translation: string;
}
export namespace Translation {
    export type TranslationTargetEnum = 'BUILDING' | 'RESEARCH' | 'MISSILE' | 'LAUNCHER' | 'ARMOR' | 'ELECTRONIC_WARFARE' | 'PROPULSION' | 'WEAPON' | 'PASSIVE_MODULE' | 'SIDEWALL' | 'ORBITAL_MODULE';
    export const TranslationTargetEnum = {
        BUILDING: 'BUILDING' as TranslationTargetEnum,
        RESEARCH: 'RESEARCH' as TranslationTargetEnum,
        MISSILE: 'MISSILE' as TranslationTargetEnum,
        LAUNCHER: 'LAUNCHER' as TranslationTargetEnum,
        ARMOR: 'ARMOR' as TranslationTargetEnum,
        ELECTRONIC_WARFARE: 'ELECTRONIC_WARFARE' as TranslationTargetEnum,
        PROPULSION: 'PROPULSION' as TranslationTargetEnum,
        WEAPON: 'WEAPON' as TranslationTargetEnum,
        PASSIVE_MODULE: 'PASSIVE_MODULE' as TranslationTargetEnum,
        SIDEWALL: 'SIDEWALL' as TranslationTargetEnum,
        ORBITAL_MODULE: 'ORBITAL_MODULE' as TranslationTargetEnum
    };
    export type TranslatableTypeEnum = 'NAME' | 'DESCRIPTION';
    export const TranslatableTypeEnum = {
        NAME: 'NAME' as TranslatableTypeEnum,
        DESCRIPTION: 'DESCRIPTION' as TranslatableTypeEnum
    };
}