/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface UserSettings { 
    /**
     * If the user want to receive infos about a new released version via mail.
     */
    receiveChangelogInfos: boolean;
    /**
     * If the user must not log in.
     */
    loginForbidden: boolean;
    /**
     * If the user has verified the mail address.
     */
    eMailVerified: boolean;
    /**
     * The mail address.
     */
    eMail?: string;
    /**
     * If the user does not want receive any mail.
     */
    noEMailWanted: boolean;
    /**
     * The profile pic name.
     */
    profilePic: string;
}
