/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Distance } from './distance';

/**
 * .
 */
export interface Warhead { 
    /**
     * The projected damage of this warhead.
     */
    damageValue: number;
    damageProjectionRange: Distance;
    /**
     * The warhead type.
     */
    warheadType: Warhead.WarheadTypeEnum;
}
export namespace Warhead {
    export type WarheadTypeEnum = 'LASER' | 'EXPLOSION' | 'KINETIC' | 'COUNTER_MISSILE';
    export const WarheadTypeEnum = {
        LASER: 'LASER' as WarheadTypeEnum,
        EXPLOSION: 'EXPLOSION' as WarheadTypeEnum,
        KINETIC: 'KINETIC' as WarheadTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as WarheadTypeEnum
    };
}