/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Warhead { 
    /**
     * The effective range of this warhead.
     */
    damageProjectionRange: number;
    /**
     * The projected damage of this warhead.
     */
    damageValue: number;
    /**
     * The id of this warhead.
     */
    idWarhead: number;
    /**
     * The type name of this warhead.
     */
    typeName: string;
    /**
     * The used capacity of this warhead.
     */
    useCapacity: number;
    /**
     * The warhead type.
     */
    warheadType: Warhead.WarheadTypeEnum;
}
export namespace Warhead {
    export type WarheadTypeEnum = 'COUNTER_MISSILE' | 'EXPLOSION' | 'KINETIC' | 'LASER';
    export const WarheadTypeEnum = {
        COUNTERMISSILE: 'COUNTER_MISSILE' as WarheadTypeEnum,
        EXPLOSION: 'EXPLOSION' as WarheadTypeEnum,
        KINETIC: 'KINETIC' as WarheadTypeEnum,
        LASER: 'LASER' as WarheadTypeEnum
    };
}