/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Planet } from './planet';
import { ShipClass } from './shipClass';

/**
 * .
 */
export interface WarShip { 
    /**
     * The name of this individual ship.
     */
    name: string;
    shipyard: Planet;
    /**
     * The fleet which this ship is part of.
     */
    idFleet: number;
    shipClass: ShipClass;
}