/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpacecraftCapabilities } from './spacecraftCapabilities';

/**
 * .
 */
export interface WarshipHealthState { 
    spacecraftCapabilities: SpacecraftCapabilities;
    /**
     * If the ship is alive after damage.
     */
    isAlive: boolean;
    /**
     * If the ship is capable of staying in the battle after damage.
     */
    isFightingCapable: boolean;
}
