/**
 * BoF REST API
 * description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AmmunitionModule } from './ammunitionModule';
import { BaseModule } from './baseModule';

export interface Weapon { 
    /**
     * The possible mount points of this weapon.
     */
    alignmentTypes: Array<Weapon.AlignmentTypesEnum>;
    ammunitionModule?: AmmunitionModule;
    baseModule: BaseModule;
    /**
     * The kind of damage which will be projected.
     */
    damageType: Weapon.DamageTypeEnum;
    /**
     * The effective range of this weapon.
     */
    effectiveRange: number;
    /**
     * The possibility of penetrating the sidewall.
     */
    sideWallPenetration?: number;
    /**
     * The way how the damage will be projected.
     */
    weaponType: Weapon.WeaponTypeEnum;
}
export namespace Weapon {
    export type AlignmentTypesEnum = 'BOW' | 'BROADSIDE' | 'STERN';
    export const AlignmentTypesEnum = {
        BOW: 'BOW' as AlignmentTypesEnum,
        BROADSIDE: 'BROADSIDE' as AlignmentTypesEnum,
        STERN: 'STERN' as AlignmentTypesEnum
    };
    export type DamageTypeEnum = 'DART' | 'EXPLOSION';
    export const DamageTypeEnum = {
        DART: 'DART' as DamageTypeEnum,
        EXPLOSION: 'EXPLOSION' as DamageTypeEnum
    };
    export type WeaponTypeEnum = 'BEAM' | 'COUNTER_MISSILE' | 'MISSILE' | 'POINT_DEFENSE';
    export const WeaponTypeEnum = {
        BEAM: 'BEAM' as WeaponTypeEnum,
        COUNTERMISSILE: 'COUNTER_MISSILE' as WeaponTypeEnum,
        MISSILE: 'MISSILE' as WeaponTypeEnum,
        POINTDEFENSE: 'POINT_DEFENSE' as WeaponTypeEnum
    };
}