/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Alliance } from '../model/alliance';
import { FrontendError } from '../model/frontendError';
import { UserJson } from '../model/userJson';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AllianceApiService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Starts the application of a user to an alliances.
     * 
     * @param idAlliance 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public applyForMembership(idAlliance: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public applyForMembership(idAlliance: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public applyForMembership(idAlliance: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public applyForMembership(idAlliance: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAlliance === null || idAlliance === undefined) {
            throw new Error('Required parameter idAlliance was null or undefined when calling applyForMembership.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/alliances/membership/${encodeURIComponent(String(idAlliance))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Checks if a username already exists.
     * 
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkAllianceName(name: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public checkAllianceName(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public checkAllianceName(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public checkAllianceName(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling checkAllianceName.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/alliances/checkAllianceName/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Checks if a eMail already exists.
     * 
     * @param eMail 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkCode(eMail: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public checkCode(eMail: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public checkCode(eMail: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public checkCode(eMail: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (eMail === null || eMail === undefined) {
            throw new Error('Required parameter eMail was null or undefined when calling checkCode.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/alliances/checkEmail/${encodeURIComponent(String(eMail))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create an alliances.
     * 
     * @param name 
     * @param code 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAlliance(name: string, code: string, observe?: 'body', reportProgress?: boolean): Observable<Alliance>;
    public createAlliance(name: string, code: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Alliance>>;
    public createAlliance(name: string, code: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Alliance>>;
    public createAlliance(name: string, code: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling createAlliance.');
        }

        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling createAlliance.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Alliance>('post',`${this.basePath}/api/private/alliances/${encodeURIComponent(String(name))}/${encodeURIComponent(String(code))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Adds a user to an alliances.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAlliance(observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteAlliance(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteAlliance(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteAlliance(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/api/private/alliances/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Denies the application of user to an alliances.
     * 
     * @param idUserToRemove 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public denyApplication(idUserToRemove: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public denyApplication(idUserToRemove: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public denyApplication(idUserToRemove: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public denyApplication(idUserToRemove: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUserToRemove === null || idUserToRemove === undefined) {
            throw new Error('Required parameter idUserToRemove was null or undefined when calling denyApplication.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/api/private/alliances/membership/${encodeURIComponent(String(idUserToRemove))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets an alliances.
     * 
     * @param idAlliance 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAlliance(idAlliance: number, observe?: 'body', reportProgress?: boolean): Observable<Alliance>;
    public getAlliance(idAlliance: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Alliance>>;
    public getAlliance(idAlliance: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Alliance>>;
    public getAlliance(idAlliance: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAlliance === null || idAlliance === undefined) {
            throw new Error('Required parameter idAlliance was null or undefined when calling getAlliance.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Alliance>('get',`${this.basePath}/api/private/alliances/${encodeURIComponent(String(idAlliance))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets an alliances.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllianceForUser(observe?: 'body', reportProgress?: boolean): Observable<Alliance>;
    public getAllianceForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Alliance>>;
    public getAllianceForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Alliance>>;
    public getAllianceForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Alliance>('get',`${this.basePath}/api/private/alliances/forUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all alliances.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAlliances(observe?: 'body', reportProgress?: boolean): Observable<Array<Alliance>>;
    public getAlliances(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Alliance>>>;
    public getAlliances(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Alliance>>>;
    public getAlliances(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Alliance>>('get',`${this.basePath}/api/private/alliances/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Fetches the applications of users to the alliance of the ally admin.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApplicationsForMembership(observe?: 'body', reportProgress?: boolean): Observable<Array<UserJson>>;
    public getApplicationsForMembership(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserJson>>>;
    public getApplicationsForMembership(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserJson>>>;
    public getApplicationsForMembership(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<UserJson>>('get',`${this.basePath}/api/private/alliances/membership/application`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets an alliances.
     * 
     * @param idAlliance 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMembers(idAlliance: number, observe?: 'body', reportProgress?: boolean): Observable<Array<UserJson>>;
    public getMembers(idAlliance: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserJson>>>;
    public getMembers(idAlliance: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserJson>>>;
    public getMembers(idAlliance: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAlliance === null || idAlliance === undefined) {
            throw new Error('Required parameter idAlliance was null or undefined when calling getMembers.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<UserJson>>('get',`${this.basePath}/api/private/alliances/members/${encodeURIComponent(String(idAlliance))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Grants the application of a user to an alliances.
     * 
     * @param idUserToAdd 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public grantApplication(idUserToAdd: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public grantApplication(idUserToAdd: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public grantApplication(idUserToAdd: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public grantApplication(idUserToAdd: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUserToAdd === null || idUserToAdd === undefined) {
            throw new Error('Required parameter idUserToAdd was null or undefined when calling grantApplication.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/alliances/membership/${encodeURIComponent(String(idUserToAdd))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns where the user has an application to an alliance open.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public isApplicant(observe?: 'body', reportProgress?: boolean): Observable<Alliance>;
    public isApplicant(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Alliance>>;
    public isApplicant(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Alliance>>;
    public isApplicant(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Alliance>('get',`${this.basePath}/api/private/alliances/membership/isApplicant`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
