export * from './adminApi.service';
import { AdminApiService } from './adminApi.service';
export * from './allianceApi.service';
import { AllianceApiService } from './allianceApi.service';
export * from './authApi.service';
import { AuthApiService } from './authApi.service';
export * from './battleReportApi.service';
import { BattleReportApiService } from './battleReportApi.service';
export * from './buildingApi.service';
import { BuildingApiService } from './buildingApi.service';
export * from './chatApi.service';
import { ChatApiService } from './chatApi.service';
export * from './colonizationApi.service';
import { ColonizationApiService } from './colonizationApi.service';
export * from './constructionApi.service';
import { ConstructionApiService } from './constructionApi.service';
export * from './fakeApi.service';
import { FakeApiService } from './fakeApi.service';
export * from './fleetApi.service';
import { FleetApiService } from './fleetApi.service';
export * from './forumApi.service';
import { ForumApiService } from './forumApi.service';
export * from './jobApi.service';
import { JobApiService } from './jobApi.service';
export * from './moduleApi.service';
import { ModuleApiService } from './moduleApi.service';
export * from './planetApi.service';
import { PlanetApiService } from './planetApi.service';
export * from './researchApi.service';
import { ResearchApiService } from './researchApi.service';
export * from './resourcesApi.service';
import { ResourcesApiService } from './resourcesApi.service';
export * from './shipyardApi.service';
import { ShipyardApiService } from './shipyardApi.service';
export * from './starMapApi.service';
import { StarMapApiService } from './starMapApi.service';
export * from './tickApi.service';
import { TickApiService } from './tickApi.service';
export * from './userApi.service';
import { UserApiService } from './userApi.service';
export const APIS = [AdminApiService, AllianceApiService, AuthApiService, BattleReportApiService, BuildingApiService, ChatApiService, ColonizationApiService, ConstructionApiService, FakeApiService, FleetApiService, ForumApiService, JobApiService, ModuleApiService, PlanetApiService, ResearchApiService, ResourcesApiService, ShipyardApiService, StarMapApiService, TickApiService, UserApiService];
