export * from './authApi.service';
import { AuthApiService } from './authApi.service';
export * from './buildingApi.service';
import { BuildingApiService } from './buildingApi.service';
export * from './chatApi.service';
import { ChatApiService } from './chatApi.service';
export * from './constructionApi.service';
import { ConstructionApiService } from './constructionApi.service';
export * from './fleetApi.service';
import { FleetApiService } from './fleetApi.service';
export * from './jobApi.service';
import { JobApiService } from './jobApi.service';
export * from './moduleApi.service';
import { ModuleApiService } from './moduleApi.service';
export * from './planetApi.service';
import { PlanetApiService } from './planetApi.service';
export * from './researchApi.service';
import { ResearchApiService } from './researchApi.service';
export * from './shipyardApi.service';
import { ShipyardApiService } from './shipyardApi.service';
export * from './starMapApi.service';
import { StarMapApiService } from './starMapApi.service';
export * from './userApi.service';
import { UserApiService } from './userApi.service';
export const APIS = [AuthApiService, BuildingApiService, ChatApiService, ConstructionApiService, FleetApiService, JobApiService, ModuleApiService, PlanetApiService, ResearchApiService, ShipyardApiService, StarMapApiService, UserApiService];
