/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Colonization } from '../model/colonization';
import { FrontendError } from '../model/frontendError';
import { Planet } from '../model/planet';
import { ResourceDeposit } from '../model/resourceDeposit';
import { StarSystem } from '../model/starSystem';
import { StarSystemColonization } from '../model/starSystemColonization';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class ColonizationApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get all not colonized but known systems for a user.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buyInformationForSystem(body: StarSystem, observe?: 'body', reportProgress?: boolean): Observable<StarSystemColonization>;
    public buyInformationForSystem(body: StarSystem, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StarSystemColonization>>;
    public buyInformationForSystem(body: StarSystem, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StarSystemColonization>>;
    public buyInformationForSystem(body: StarSystem, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling buyInformationForSystem.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<StarSystemColonization>('post',`${this.basePath}/api/private/colonization/buy`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Fetches the time which is needed for the colonization of a planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public fetchColonizingTime(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public fetchColonizingTime(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public fetchColonizingTime(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public fetchColonizingTime(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling fetchColonizingTime.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/api/private/colonization/duration/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs to colonize the targeted planet.
     * 
     * @param planet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getColonizationCosts(planet: Planet, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getColonizationCosts(planet: Planet, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getColonizationCosts(planet: Planet, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getColonizationCosts(planet: Planet, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (planet === null || planet === undefined) {
            throw new Error('Required parameter planet was null or undefined when calling getColonizationCosts.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (planet !== undefined && planet !== null) {
            queryParameters = queryParameters.set('planet', <any>planet);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/colonization/costs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all colonizable systems for a user with their distances to all known systems.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getColonizationStarSystemsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<StarSystemColonization>>;
    public getColonizationStarSystemsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StarSystemColonization>>>;
    public getColonizationStarSystemsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StarSystemColonization>>>;
    public getColonizationStarSystemsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StarSystemColonization>>('get',`${this.basePath}/api/private/colonization/all`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all not colonized but known systems for a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHomeSystem(observe?: 'body', reportProgress?: boolean): Observable<StarSystem>;
    public getHomeSystem(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StarSystem>>;
    public getHomeSystem(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StarSystem>>;
    public getHomeSystem(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<StarSystem>('get',`${this.basePath}/api/private/colonization/home`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all not known systems for a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getKnownStarSystemsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<StarSystem>>;
    public getKnownStarSystemsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StarSystem>>>;
    public getKnownStarSystemsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StarSystem>>>;
    public getKnownStarSystemsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StarSystem>>('get',`${this.basePath}/api/private/colonization/knownSystems`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all pending colonizations for the user with their distances to all known systems.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPendingColonizationsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<StarSystemColonization>>;
    public getPendingColonizationsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StarSystemColonization>>>;
    public getPendingColonizationsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StarSystemColonization>>>;
    public getPendingColonizationsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StarSystemColonization>>('get',`${this.basePath}/api/private/colonization/pendingColonizations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all not colonized but known systems for a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUnknownStarSystemsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<StarSystem>>;
    public getUnknownStarSystemsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StarSystem>>>;
    public getUnknownStarSystemsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StarSystem>>>;
    public getUnknownStarSystemsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StarSystem>>('get',`${this.basePath}/api/private/colonization/freeSystems`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Starts the colonization of a planet for a user.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public startColonizingPlanet(body: Planet, observe?: 'body', reportProgress?: boolean): Observable<Colonization>;
    public startColonizingPlanet(body: Planet, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Colonization>>;
    public startColonizingPlanet(body: Planet, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Colonization>>;
    public startColonizingPlanet(body: Planet, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling startColonizingPlanet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Colonization>('put',`${this.basePath}/api/private/colonization/`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Stops the planned colonization of a planet for a user.
     * 
     * @param idColonization 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stopPlannedColonization(idColonization: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public stopPlannedColonization(idColonization: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public stopPlannedColonization(idColonization: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public stopPlannedColonization(idColonization: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idColonization === null || idColonization === undefined) {
            throw new Error('Required parameter idColonization was null or undefined when calling stopPlannedColonization.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/api/private/colonization/${encodeURIComponent(String(idColonization))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
