/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Fleet } from '../model/fleet';
import { FleetDistributionPerUser } from '../model/fleetDistributionPerUser';
import { FleetMerge } from '../model/fleetMerge';
import { FleetMove } from '../model/fleetMove';
import { FrontendError } from '../model/frontendError';
import { Move } from '../model/move';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from "../../../../environments/environment";


@Injectable()
export class FleetApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Cancels a movement of a fleet and creates the way back.
     * 
     * @param idUser 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cancelMovement(idUser: number, idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<Fleet>;
    public cancelMovement(idUser: number, idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Fleet>>;
    public cancelMovement(idUser: number, idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Fleet>>;
    public cancelMovement(idUser: number, idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling cancelMovement.');
        }

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling cancelMovement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.request<Fleet>('put',`${this.basePath}/api/private/fleet/cancelMove/${encodeURIComponent(String(idUser))}/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all the star systems which are holding fleets with the fleet&#x27;s owner.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetDistribution(observe?: 'body', reportProgress?: boolean): Observable<Array<FleetDistributionPerUser>>;
    public getFleetDistribution(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetDistributionPerUser>>>;
    public getFleetDistribution(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetDistributionPerUser>>>;
    public getFleetDistribution(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FleetDistributionPerUser>>('get',`${this.basePath}/api/private/fleet/fleetDistribution`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system.
     * 
     * @param idStarSystem 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsBySystem(idStarSystem: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsBySystem(idStarSystem: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsBySystem(idStarSystem: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsBySystem(idStarSystem: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idStarSystem === null || idStarSystem === undefined) {
            throw new Error('Required parameter idStarSystem was null or undefined when calling getFleetsBySystem.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/inSystem/${encodeURIComponent(String(idStarSystem))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system for a specific user.
     * 
     * @param idStarSystem 
     * @param idOwner 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idStarSystem === null || idStarSystem === undefined) {
            throw new Error('Required parameter idStarSystem was null or undefined when calling getFleetsBySystemAndOwner.');
        }

        if (idOwner === null || idOwner === undefined) {
            throw new Error('Required parameter idOwner was null or undefined when calling getFleetsBySystemAndOwner.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/inSystem/${encodeURIComponent(String(idStarSystem))}/perUser/${encodeURIComponent(String(idOwner))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets of an owner.
     * 
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsForUser(idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsForUser(idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsForUser(idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsForUser(idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling getFleetsForUser.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/perUser/${encodeURIComponent(String(idUser))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInterstellarMovingFleets(observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getInterstellarMovingFleets(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getInterstellarMovingFleets(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getInterstellarMovingFleets(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/interstellarMovement`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Merge two fleets of an owner.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Fleet>;
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Fleet>>;
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Fleet>>;
    public mergeFleets(body: FleetMerge, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling mergeFleets.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling mergeFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Fleet>('post',`${this.basePath}/api/private/fleet/merge/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Moves a fleet to another celestial.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moveFleet(body: FleetMove, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Fleet>;
    public moveFleet(body: FleetMove, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Fleet>>;
    public moveFleet(body: FleetMove, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Fleet>>;
    public moveFleet(body: FleetMove, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling moveFleet.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling moveFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Fleet>('post',`${this.basePath}/api/private/fleet/move/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Moves a fleet to another celestial.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moveFleets(body: Array<FleetMove>, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public moveFleets(body: Array<FleetMove>, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public moveFleets(body: Array<FleetMove>, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public moveFleets(body: Array<FleetMove>, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling moveFleets.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling moveFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<Fleet>>('post',`${this.basePath}/api/private/fleet/moveFleets/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Plan a movement of a fleet to another celestial.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planMovement(body: FleetMove, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Move>;
    public planMovement(body: FleetMove, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Move>>;
    public planMovement(body: FleetMove, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Move>>;
    public planMovement(body: FleetMove, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling planMovement.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling planMovement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Move>('post',`${this.basePath}/api/private/fleet/planMove/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Plan a movement of a fleet to another celestial.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planMovements(body: Array<FleetMove>, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Move>>;
    public planMovements(body: Array<FleetMove>, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Move>>>;
    public planMovements(body: Array<FleetMove>, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Move>>>;
    public planMovements(body: Array<FleetMove>, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling planMovements.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling planMovements.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<Move>>('post',`${this.basePath}/api/private/fleet/planMoves/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
