/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Fleet } from '../model/fleet';
import { FleetDistributionPerUser } from '../model/fleetDistributionPerUser';
import { FleetMarker } from '../model/fleetMarker';
import { FleetMerge } from '../model/fleetMerge';
import { FleetMove } from '../model/fleetMove';
import { FleetMovement } from '../model/fleetMovement';
import { FrontendError } from '../model/frontendError';
import { Move } from '../model/move';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class FleetApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Cancels a movement of a fleet and creates the way back.
     * 
     * @param fleetIds 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cancelMovement(fleetIds: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public cancelMovement(fleetIds: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public cancelMovement(fleetIds: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public cancelMovement(fleetIds: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleetIds === null || fleetIds === undefined) {
            throw new Error('Required parameter fleetIds was null or undefined when calling cancelMovement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/fleet/cancelMoves/${encodeURIComponent(String(fleetIds))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all finished movements of fleets of an owner.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFinishedMovements(observe?: 'body', reportProgress?: boolean): Observable<Array<FleetMovement>>;
    public getFinishedMovements(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetMovement>>>;
    public getFinishedMovements(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetMovement>>>;
    public getFinishedMovements(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FleetMovement>>('get',`${this.basePath}/api/private/fleet/finishedMovement`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the fleet.
     * 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleet(idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<Fleet>;
    public getFleet(idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Fleet>>;
    public getFleet(idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Fleet>>;
    public getFleet(idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling getFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Fleet>('get',`${this.basePath}/api/private/fleet/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all the star systems which are holding fleets with the fleet&#x27;s owner.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetDistribution(observe?: 'body', reportProgress?: boolean): Observable<Array<FleetDistributionPerUser>>;
    public getFleetDistribution(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetDistributionPerUser>>>;
    public getFleetDistribution(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetDistributionPerUser>>>;
    public getFleetDistribution(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FleetDistributionPerUser>>('get',`${this.basePath}/api/private/fleet/fleetDistribution`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside the orbit of a planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsByPlanet(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsByPlanet(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsByPlanet(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsByPlanet(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getFleetsByPlanet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/atPlanet/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system.
     * 
     * @param idStarSystem 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsBySystem(idStarSystem: number, observe?: 'body', reportProgress?: boolean): Observable<Array<FleetMarker>>;
    public getFleetsBySystem(idStarSystem: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetMarker>>>;
    public getFleetsBySystem(idStarSystem: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetMarker>>>;
    public getFleetsBySystem(idStarSystem: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idStarSystem === null || idStarSystem === undefined) {
            throw new Error('Required parameter idStarSystem was null or undefined when calling getFleetsBySystem.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FleetMarker>>('get',`${this.basePath}/api/private/fleet/inSystem/${encodeURIComponent(String(idStarSystem))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system for a specific user.
     * 
     * @param idStarSystem 
     * @param idOwner 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsBySystemAndOwner(idStarSystem: number, idOwner: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idStarSystem === null || idStarSystem === undefined) {
            throw new Error('Required parameter idStarSystem was null or undefined when calling getFleetsBySystemAndOwner.');
        }

        if (idOwner === null || idOwner === undefined) {
            throw new Error('Required parameter idOwner was null or undefined when calling getFleetsBySystemAndOwner.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/inSystem/${encodeURIComponent(String(idStarSystem))}/perUser/${encodeURIComponent(String(idOwner))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets of an owner.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getFleetsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getFleetsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getFleetsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/perUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all fleets inside of a star system.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInterstellarMovingFleets(observe?: 'body', reportProgress?: boolean): Observable<Array<FleetMarker>>;
    public getInterstellarMovingFleets(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetMarker>>>;
    public getInterstellarMovingFleets(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetMarker>>>;
    public getInterstellarMovingFleets(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FleetMarker>>('get',`${this.basePath}/api/private/fleet/interstellarMovement`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all moving fleets of an owner.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMovingFleetsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public getMovingFleetsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public getMovingFleetsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public getMovingFleetsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Fleet>>('get',`${this.basePath}/api/private/fleet/movingPerUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Merge two fleets of an owner.
     * 
     * @param body default response
     * @param idUser 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'body', reportProgress?: boolean): Observable<Fleet>;
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Fleet>>;
    public mergeFleets(body: FleetMerge, idUser: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Fleet>>;
    public mergeFleets(body: FleetMerge, idUser: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling mergeFleets.');
        }

        if (idUser === null || idUser === undefined) {
            throw new Error('Required parameter idUser was null or undefined when calling mergeFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Fleet>('post',`${this.basePath}/api/private/fleet/merge/${encodeURIComponent(String(idUser))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Moves a fleet to another celestial.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moveFleets(body: Array<FleetMove>, observe?: 'body', reportProgress?: boolean): Observable<Array<Fleet>>;
    public moveFleets(body: Array<FleetMove>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Fleet>>>;
    public moveFleets(body: Array<FleetMove>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Fleet>>>;
    public moveFleets(body: Array<FleetMove>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling moveFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<Fleet>>('post',`${this.basePath}/api/private/fleet/moveFleets`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Plan a movement of a fleet to another celestial.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planMovements(body: Array<FleetMove>, observe?: 'body', reportProgress?: boolean): Observable<Array<Move>>;
    public planMovements(body: Array<FleetMove>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Move>>>;
    public planMovements(body: Array<FleetMove>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Move>>>;
    public planMovements(body: Array<FleetMove>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling planMovements.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<Move>>('post',`${this.basePath}/api/private/fleet/planMoves`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Renames a fleet.
     * 
     * @param idFleet 
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public renameFleet(idFleet: number, name: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public renameFleet(idFleet: number, name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public renameFleet(idFleet: number, name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public renameFleet(idFleet: number, name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling renameFleet.');
        }

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling renameFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/fleet/rename/${encodeURIComponent(String(idFleet))}/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
