/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateForumThread } from '../model/createForumThread';
import { CreateForumThreadMessage } from '../model/createForumThreadMessage';
import { Forum } from '../model/forum';
import { ForumMessage } from '../model/forumMessage';
import { ForumThread } from '../model/forumThread';
import { FrontendError } from '../model/frontendError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ForumApiService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param idForumThread 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public countMessagesInThread(idForumThread: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public countMessagesInThread(idForumThread: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public countMessagesInThread(idForumThread: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public countMessagesInThread(idForumThread: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idForumThread === null || idForumThread === undefined) {
            throw new Error('Required parameter idForumThread was null or undefined when calling countMessagesInThread.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/api/private/forum/threadById/count/${encodeURIComponent(String(idForumThread))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createForumThread(body?: CreateForumThread, observe?: 'body', reportProgress?: boolean): Observable<ForumThread>;
    public createForumThread(body?: CreateForumThread, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ForumThread>>;
    public createForumThread(body?: CreateForumThread, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ForumThread>>;
    public createForumThread(body?: CreateForumThread, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ForumThread>('put',`${this.basePath}/api/private/forum/createThread`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createThreadMessage(body?: CreateForumThreadMessage, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public createThreadMessage(body?: CreateForumThreadMessage, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public createThreadMessage(body?: CreateForumThreadMessage, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public createThreadMessage(body?: CreateForumThreadMessage, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/forum/createThreadMessage`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllianceForumForUser(observe?: 'body', reportProgress?: boolean): Observable<Forum>;
    public getAllianceForumForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Forum>>;
    public getAllianceForumForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Forum>>;
    public getAllianceForumForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Forum>('get',`${this.basePath}/api/private/forum/allianceForumsForUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param idForumThread 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getForumThreadById(idForumThread: number, observe?: 'body', reportProgress?: boolean): Observable<ForumThread>;
    public getForumThreadById(idForumThread: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ForumThread>>;
    public getForumThreadById(idForumThread: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ForumThread>>;
    public getForumThreadById(idForumThread: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idForumThread === null || idForumThread === undefined) {
            throw new Error('Required parameter idForumThread was null or undefined when calling getForumThreadById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ForumThread>('get',`${this.basePath}/api/private/forum/threadById/${encodeURIComponent(String(idForumThread))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of threads in a forum which the given user is allowed to access.
     * 
     * @param idForum 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getForumThreadsByForumId(idForum: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ForumThread>>;
    public getForumThreadsByForumId(idForum: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ForumThread>>>;
    public getForumThreadsByForumId(idForum: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ForumThread>>>;
    public getForumThreadsByForumId(idForum: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idForum === null || idForum === undefined) {
            throw new Error('Required parameter idForum was null or undefined when calling getForumThreadsByForumId.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ForumThread>>('get',`${this.basePath}/api/private/forum/threadById/byForum/${encodeURIComponent(String(idForum))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getForumsForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Forum>>;
    public getForumsForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Forum>>>;
    public getForumsForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Forum>>>;
    public getForumsForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Forum>>('get',`${this.basePath}/api/private/forum/forumsForUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a list of forums which the given user is allowed to access.
     * 
     * @param idForumThread 
     * @param page 
     * @param size 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMessagesInThread(idForumThread: number, page: number, size: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ForumMessage>>;
    public getMessagesInThread(idForumThread: number, page: number, size: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ForumMessage>>>;
    public getMessagesInThread(idForumThread: number, page: number, size: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ForumMessage>>>;
    public getMessagesInThread(idForumThread: number, page: number, size: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idForumThread === null || idForumThread === undefined) {
            throw new Error('Required parameter idForumThread was null or undefined when calling getMessagesInThread.');
        }

        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling getMessagesInThread.');
        }

        if (size === null || size === undefined) {
            throw new Error('Required parameter size was null or undefined when calling getMessagesInThread.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ForumMessage>>('get',`${this.basePath}/api/private/forum/threadById/${encodeURIComponent(String(idForumThread))}/${encodeURIComponent(String(page))}/${encodeURIComponent(String(size))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
