/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { FrontendError } from '../model/frontendError';
import { SpotOffer } from '../model/spotOffer';
import { TakeOffer } from '../model/takeOffer';
import { TradeContract } from '../model/tradeContract';
import { TradeOffer } from '../model/tradeOffer';
import { TradesByLocation } from '../model/tradesByLocation';
import { ValueTradesByTick } from '../model/valueTradesByTick';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class MarketplaceApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get all EResourceTypes.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buyAtSpotMarket(body: SpotOffer, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public buyAtSpotMarket(body: SpotOffer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public buyAtSpotMarket(body: SpotOffer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public buyAtSpotMarket(body: SpotOffer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling buyAtSpotMarket.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/trade/spot/buy`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes an trade offer.
     * 
     * @param idTradeOffer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOffer(idTradeOffer: number, observe?: 'body', reportProgress?: boolean): Observable<Array<boolean>>;
    public deleteOffer(idTradeOffer: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<boolean>>>;
    public deleteOffer(idTradeOffer: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<boolean>>>;
    public deleteOffer(idTradeOffer: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idTradeOffer === null || idTradeOffer === undefined) {
            throw new Error('Required parameter idTradeOffer was null or undefined when calling deleteOffer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<boolean>>('delete',`${this.basePath}/api/private/trade/offer/${encodeURIComponent(String(idTradeOffer))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all today contracted trades.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFreshTradesForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<TradeContract>>;
    public getFreshTradesForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TradeContract>>>;
    public getFreshTradesForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TradeContract>>>;
    public getFreshTradesForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TradeContract>>('get',`${this.basePath}/api/private/trade/historyForUser/fresh`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOffers(observe?: 'body', reportProgress?: boolean): Observable<Array<TradeOffer>>;
    public getOffers(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TradeOffer>>>;
    public getOffers(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TradeOffer>>>;
    public getOffers(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TradeOffer>>('get',`${this.basePath}/api/private/trade/offer`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param resourceType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpotPrice(resourceType: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public getSpotPrice(resourceType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public getSpotPrice(resourceType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public getSpotPrice(resourceType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (resourceType === null || resourceType === undefined) {
            throw new Error('Required parameter resourceType was null or undefined when calling getSpotPrice.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/api/private/trade/spot/pricePerUnit/${encodeURIComponent(String(resourceType))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param pastTicks 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTrades(pastTicks: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ValueTradesByTick>>;
    public getTrades(pastTicks: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ValueTradesByTick>>>;
    public getTrades(pastTicks: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ValueTradesByTick>>>;
    public getTrades(pastTicks: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pastTicks === null || pastTicks === undefined) {
            throw new Error('Required parameter pastTicks was null or undefined when calling getTrades.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ValueTradesByTick>>('get',`${this.basePath}/api/private/trade/history/${encodeURIComponent(String(pastTicks))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all today relevant trades.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTradesForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<TradesByLocation>>;
    public getTradesForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TradesByLocation>>>;
    public getTradesForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TradesByLocation>>>;
    public getTradesForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TradesByLocation>>('get',`${this.basePath}/api/private/trade/historyForUser`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sellAtSpotMarket(body: SpotOffer, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public sellAtSpotMarket(body: SpotOffer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public sellAtSpotMarket(body: SpotOffer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public sellAtSpotMarket(body: SpotOffer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling sellAtSpotMarket.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/trade/spot/sell`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Creates an offer
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setOffer(body: TradeOffer, observe?: 'body', reportProgress?: boolean): Observable<TradeOffer>;
    public setOffer(body: TradeOffer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TradeOffer>>;
    public setOffer(body: TradeOffer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TradeOffer>>;
    public setOffer(body: TradeOffer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling setOffer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<TradeOffer>('put',`${this.basePath}/api/private/trade/offer`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public takeOffer(body: TakeOffer, observe?: 'body', reportProgress?: boolean): Observable<TradeContract>;
    public takeOffer(body: TakeOffer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TradeContract>>;
    public takeOffer(body: TakeOffer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TradeContract>>;
    public takeOffer(body: TakeOffer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling takeOffer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<TradeContract>('post',`${this.basePath}/api/private/trade/offer`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
