/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.0.1
 * Contact: bla@bla.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Armor } from '../model/armor';
import { ElectronicWarfare } from '../model/electronicWarfare';
import { FrontendError } from '../model/frontendError';
import { Hull } from '../model/hull';
import { Launcher } from '../model/launcher';
import { PassiveModule } from '../model/passiveModule';
import { Propulsion } from '../model/propulsion';
import { Sidewall } from '../model/sidewall';
import { Weapon } from '../model/weapon';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class ModuleApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get all unlocked armors for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getArmorsByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Armor>>;
    public getArmorsByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Armor>>>;
    public getArmorsByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Armor>>>;
    public getArmorsByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Armor>>('get',`${this.basePath}/api/private/modules/armor`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked electronic warfare for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getElectronicWarfareByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<ElectronicWarfare>>;
    public getElectronicWarfareByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ElectronicWarfare>>>;
    public getElectronicWarfareByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ElectronicWarfare>>>;
    public getElectronicWarfareByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ElectronicWarfare>>('get',`${this.basePath}/api/private/modules/eloka`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked hulls for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHullsByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Hull>>;
    public getHullsByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Hull>>>;
    public getHullsByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Hull>>>;
    public getHullsByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Hull>>('get',`${this.basePath}/api/private/modules/hull`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked weapons for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLaunchersByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Launcher>>;
    public getLaunchersByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Launcher>>>;
    public getLaunchersByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Launcher>>>;
    public getLaunchersByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Launcher>>('get',`${this.basePath}/api/private/modules/launcher`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked passive modules for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPassiveModulesByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<PassiveModule>>;
    public getPassiveModulesByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PassiveModule>>>;
    public getPassiveModulesByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PassiveModule>>>;
    public getPassiveModulesByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<PassiveModule>>('get',`${this.basePath}/api/private/modules/passive`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked propulsions for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPropulsionsByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Propulsion>>;
    public getPropulsionsByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Propulsion>>>;
    public getPropulsionsByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Propulsion>>>;
    public getPropulsionsByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Propulsion>>('get',`${this.basePath}/api/private/modules/propulsion`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked sidewalls for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSidewallsByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Sidewall>>;
    public getSidewallsByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Sidewall>>>;
    public getSidewallsByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Sidewall>>>;
    public getSidewallsByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Sidewall>>('get',`${this.basePath}/api/private/modules/sidewall`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all unlocked weapons for the owner .
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getWeaponsByUser(observe?: 'body', reportProgress?: boolean): Observable<Array<Weapon>>;
    public getWeaponsByUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Weapon>>>;
    public getWeaponsByUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Weapon>>>;
    public getWeaponsByUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Weapon>>('get',`${this.basePath}/api/private/modules/weapon`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
