/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { FleetOrbit } from '../model/fleetOrbit';
import { FrontendError } from '../model/frontendError';
import { Job } from '../model/job';
import { Orbit } from '../model/orbit';
import { Planet } from '../model/planet';
import { ResourceDeposit } from '../model/resourceDeposit';
import { ShipyardConstructionOrder } from '../model/shipyardConstructionOrder';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class PlanetApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Starts a construction on this planet.
     * 
     * @param idPlanet 
     * @param idBuilding 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildConstruction(idPlanet: number, idBuilding: number, observe?: 'body', reportProgress?: boolean): Observable<Job>;
    public buildConstruction(idPlanet: number, idBuilding: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Job>>;
    public buildConstruction(idPlanet: number, idBuilding: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Job>>;
    public buildConstruction(idPlanet: number, idBuilding: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling buildConstruction.');
        }

        if (idBuilding === null || idBuilding === undefined) {
            throw new Error('Required parameter idBuilding was null or undefined when calling buildConstruction.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Job>('get',`${this.basePath}/api/private/planet/groundConstructionBuild/${encodeURIComponent(String(idPlanet))}/${encodeURIComponent(String(idBuilding))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Starts a construction on this planet.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildOrbitalModule(body: ShipyardConstructionOrder, observe?: 'body', reportProgress?: boolean): Observable<Job>;
    public buildOrbitalModule(body: ShipyardConstructionOrder, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Job>>;
    public buildOrbitalModule(body: ShipyardConstructionOrder, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Job>>;
    public buildOrbitalModule(body: ShipyardConstructionOrder, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling buildOrbitalModule.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Job>('post',`${this.basePath}/api/private/planet/shipyardConstructionOrbitalBuild`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Starts a construction on this planet.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildShip(body: ShipyardConstructionOrder, observe?: 'body', reportProgress?: boolean): Observable<Job>;
    public buildShip(body: ShipyardConstructionOrder, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Job>>;
    public buildShip(body: ShipyardConstructionOrder, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Job>>;
    public buildShip(body: ShipyardConstructionOrder, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling buildShip.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Job>('post',`${this.basePath}/api/private/planet/shipyardConstructionBuild`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the main planet of a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMainPlanet(observe?: 'body', reportProgress?: boolean): Observable<Planet>;
    public getMainPlanet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Planet>>;
    public getMainPlanet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Planet>>;
    public getMainPlanet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Planet>('get',`${this.basePath}/api/private/planet/main`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the main planet of a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMainPlanetCoords(observe?: 'body', reportProgress?: boolean): Observable<FleetOrbit>;
    public getMainPlanetCoords(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FleetOrbit>>;
    public getMainPlanetCoords(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FleetOrbit>>;
    public getMainPlanetCoords(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<FleetOrbit>('get',`${this.basePath}/api/private/planet/main/coords`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets a planet which is matching to the given coordinates.
     * 
     * @param body default response
     * @param idStarSystem 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlanetByCoordinates(body: Orbit, idStarSystem: number, observe?: 'body', reportProgress?: boolean): Observable<Planet>;
    public getPlanetByCoordinates(body: Orbit, idStarSystem: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Planet>>;
    public getPlanetByCoordinates(body: Orbit, idStarSystem: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Planet>>;
    public getPlanetByCoordinates(body: Orbit, idStarSystem: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getPlanetByCoordinates.');
        }

        if (idStarSystem === null || idStarSystem === undefined) {
            throw new Error('Required parameter idStarSystem was null or undefined when calling getPlanetByCoordinates.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Planet>('post',`${this.basePath}/api/private/planet/byCoord/${encodeURIComponent(String(idStarSystem))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all planets which are colonized by a user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlanetByUsers(observe?: 'body', reportProgress?: boolean): Observable<Array<Planet>>;
    public getPlanetByUsers(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Planet>>>;
    public getPlanetByUsers(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Planet>>>;
    public getPlanetByUsers(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Planet>>('get',`${this.basePath}/api/private/planet/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the transportation delivery of this planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTransportationDelivery(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getTransportationDelivery(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getTransportationDelivery(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getTransportationDelivery(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getTransportationDelivery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/planet/transportation/delivery/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the transportation need of this planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTransportationDemand(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getTransportationDemand(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getTransportationDemand(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getTransportationDemand(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getTransportationDemand.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/planet/transportation/demand/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Asks if a building could be build on this planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public isConstructionPossibleOnPlanet(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public isConstructionPossibleOnPlanet(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public isConstructionPossibleOnPlanet(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public isConstructionPossibleOnPlanet(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling isConstructionPossibleOnPlanet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('get',`${this.basePath}/api/private/planet/groundConstructionPossible/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Asks if a ship could be build on this planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public isShipyardExistsOnPlanet(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public isShipyardExistsOnPlanet(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public isShipyardExistsOnPlanet(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public isShipyardExistsOnPlanet(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling isShipyardExistsOnPlanet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('get',`${this.basePath}/api/private/planet/shipyardExists/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Asks if a ship could be build on this planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public isShipyardJobPossibleOnPlanet(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public isShipyardJobPossibleOnPlanet(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public isShipyardJobPossibleOnPlanet(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public isShipyardJobPossibleOnPlanet(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling isShipyardJobPossibleOnPlanet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('get',`${this.basePath}/api/private/planet/shipyardConstructionPossible/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Repairs the fleet.
     * 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public repairFleets(idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public repairFleets(idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public repairFleets(idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public repairFleets(idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling repairFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/planet/shipyardConstructionBuild/repair/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Sets the transportation delivery.
     * 
     * @param body default response
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setTransportationDelivery(body: ResourceDeposit, idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public setTransportationDelivery(body: ResourceDeposit, idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public setTransportationDelivery(body: ResourceDeposit, idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public setTransportationDelivery(body: ResourceDeposit, idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling setTransportationDelivery.');
        }

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling setTransportationDelivery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResourceDeposit>('put',`${this.basePath}/api/private/planet/transportation/delivery/${encodeURIComponent(String(idPlanet))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Sets the transportation demand.
     * 
     * @param body default response
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setTransportationDemand(body: ResourceDeposit, idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public setTransportationDemand(body: ResourceDeposit, idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public setTransportationDemand(body: ResourceDeposit, idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public setTransportationDemand(body: ResourceDeposit, idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling setTransportationDemand.');
        }

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling setTransportationDemand.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResourceDeposit>('put',`${this.basePath}/api/private/planet/transportation/demand/${encodeURIComponent(String(idPlanet))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Upgrades the fleet to the last successor classes.
     * 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public upgradeFleets(idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public upgradeFleets(idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public upgradeFleets(idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public upgradeFleets(idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling upgradeFleets.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/planet/shipyardConstructionBuild/upgrade/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
