/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.3
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EEducationType } from '../model/eEducationType';
import { EResourceType } from '../model/eResourceType';
import { FrontendError } from '../model/frontendError';
import { MiningFactors } from '../model/miningFactors';
import { PlannedConstruction } from '../model/plannedConstruction';
import { ResourceDeposit } from '../model/resourceDeposit';
import { ResourceTransfer } from '../model/resourceTransfer';
import { ShipClassMock } from '../model/shipClassMock';
import { ShipyardConstructionSelection } from '../model/shipyardConstructionSelection';
import { SpacecraftCapabilities } from '../model/spacecraftCapabilities';
import { SpacecraftCapacityAreas } from '../model/spacecraftCapacityAreas';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class ResourcesApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get the costs of the given construction.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBuildingCosts(body: PlannedConstruction, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getBuildingCosts(body: PlannedConstruction, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getBuildingCosts(body: PlannedConstruction, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getBuildingCosts(body: PlannedConstruction, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getBuildingCosts.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResourceDeposit>('post',`${this.basePath}/api/private/resources/costs`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCostsForFleet(idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getCostsForFleet(idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getCostsForFleet(idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getCostsForFleet(idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling getCostsForFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/costsFleet/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param idShipClass 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCostsForShipClass(idShipClass: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getCostsForShipClass(idShipClass: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getCostsForShipClass(idShipClass: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getCostsForShipClass(idShipClass: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idShipClass === null || idShipClass === undefined) {
            throw new Error('Required parameter idShipClass was null or undefined when calling getCostsForShipClass.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/costsShipClass/${encodeURIComponent(String(idShipClass))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EEducationTypes.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEEducationTypes(observe?: 'body', reportProgress?: boolean): Observable<Array<EEducationType>>;
    public getEEducationTypes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EEducationType>>>;
    public getEEducationTypes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EEducationType>>>;
    public getEEducationTypes(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<EEducationType>>('get',`${this.basePath}/api/private/resources/educationTypes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all EResourceTypes.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEResourceTypes(observe?: 'body', reportProgress?: boolean): Observable<Array<EResourceType>>;
    public getEResourceTypes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EResourceType>>>;
    public getEResourceTypes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EResourceType>>>;
    public getEResourceTypes(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<EResourceType>>('get',`${this.basePath}/api/private/resources/types`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the mining factors of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMiningFactors(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<MiningFactors>;
    public getMiningFactors(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MiningFactors>>;
    public getMiningFactors(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MiningFactors>>;
    public getMiningFactors(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getMiningFactors.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<MiningFactors>('get',`${this.basePath}/api/private/resources/miningFactors/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the capacity of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlanetaryCapacity(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getPlanetaryCapacity(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getPlanetaryCapacity(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getPlanetaryCapacity(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getPlanetaryCapacity.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/capacity/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the income of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlanetaryIncome(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getPlanetaryIncome(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getPlanetaryIncome(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getPlanetaryIncome(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getPlanetaryIncome.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/income/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the demand of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceDemand(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getResourceDemand(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getResourceDemand(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getResourceDemand(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getResourceDemand.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/demand/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the deposit of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceDeposit(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getResourceDeposit(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getResourceDeposit(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getResourceDeposit(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getResourceDeposit.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/deposit/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the deposit of the fleet.
     * 
     * @param idFleet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceDepositForFleet(idFleet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getResourceDepositForFleet(idFleet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getResourceDepositForFleet(idFleet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getResourceDepositForFleet(idFleet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFleet === null || idFleet === undefined) {
            throw new Error('Required parameter idFleet was null or undefined when calling getResourceDepositForFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/deposit/fleet/${encodeURIComponent(String(idFleet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the combined deposits from all planets of the user.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceDepositForUser(observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getResourceDepositForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getResourceDepositForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getResourceDepositForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/deposit`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the used population of the planet.
     * 
     * @param idPlanet 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceUtilization(idPlanet: number, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getResourceUtilization(idPlanet: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getResourceUtilization(idPlanet: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getResourceUtilization(idPlanet: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPlanet === null || idPlanet === undefined) {
            throw new Error('Required parameter idPlanet was null or undefined when calling getResourceUtilization.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ResourceDeposit>('get',`${this.basePath}/api/private/resources/utilization/${encodeURIComponent(String(idPlanet))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipClassCapabilities(body: ShipClassMock, observe?: 'body', reportProgress?: boolean): Observable<SpacecraftCapabilities>;
    public getShipClassCapabilities(body: ShipClassMock, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SpacecraftCapabilities>>;
    public getShipClassCapabilities(body: ShipClassMock, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SpacecraftCapabilities>>;
    public getShipClassCapabilities(body: ShipClassMock, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getShipClassCapabilities.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SpacecraftCapabilities>('post',`${this.basePath}/api/private/resources/capsShipClass`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipClassCapacities(body: ShipClassMock, observe?: 'body', reportProgress?: boolean): Observable<SpacecraftCapacityAreas>;
    public getShipClassCapacities(body: ShipClassMock, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SpacecraftCapacityAreas>>;
    public getShipClassCapacities(body: ShipClassMock, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SpacecraftCapacityAreas>>;
    public getShipClassCapacities(body: ShipClassMock, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getShipClassCapacities.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SpacecraftCapacityAreas>('post',`${this.basePath}/api/private/resources/capacitiesShipClass`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipClassCosts(body: ShipClassMock, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getShipClassCosts(body: ShipClassMock, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getShipClassCosts(body: ShipClassMock, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getShipClassCosts(body: ShipClassMock, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getShipClassCosts.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResourceDeposit>('post',`${this.basePath}/api/private/resources/costsShipClass`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipyardOrderCosts(body: Array<ShipyardConstructionSelection>, observe?: 'body', reportProgress?: boolean): Observable<ResourceDeposit>;
    public getShipyardOrderCosts(body: Array<ShipyardConstructionSelection>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResourceDeposit>>;
    public getShipyardOrderCosts(body: Array<ShipyardConstructionSelection>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResourceDeposit>>;
    public getShipyardOrderCosts(body: Array<ShipyardConstructionSelection>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getShipyardOrderCosts.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResourceDeposit>('post',`${this.basePath}/api/private/resources/costsShipyard`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the costs of the given shipyard order.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public transferResources(body: Array<ResourceTransfer>, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public transferResources(body: Array<ResourceTransfer>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public transferResources(body: Array<ResourceTransfer>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public transferResources(body: Array<ResourceTransfer>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling transferResources.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<boolean>('post',`${this.basePath}/api/private/resources/transfer`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
