/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { FrontendError } from '../model/frontendError';
import { RolePlayData } from '../model/rolePlayData';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class RolePlayApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get the list of ship names
     * 
     * @param starNation 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addShipNameTemplate(starNation: string, observe?: 'body', reportProgress?: boolean): Observable<RolePlayData>;
    public addShipNameTemplate(starNation: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RolePlayData>>;
    public addShipNameTemplate(starNation: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RolePlayData>>;
    public addShipNameTemplate(starNation: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (starNation === null || starNation === undefined) {
            throw new Error('Required parameter starNation was null or undefined when calling addShipNameTemplate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RolePlayData>('put',`${this.basePath}/api/private/rpg/shipTemplate/${encodeURIComponent(String(starNation))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addShipNamesFor(name: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public addShipNamesFor(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public addShipNamesFor(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public addShipNamesFor(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling addShipNamesFor.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/rpg/shipNames/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipNameTemplates(observe?: 'body', reportProgress?: boolean): Observable<RolePlayData>;
    public getShipNameTemplates(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RolePlayData>>;
    public getShipNameTemplates(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RolePlayData>>;
    public getShipNameTemplates(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RolePlayData>('get',`${this.basePath}/api/private/rpg/shipTemplate`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param starNation 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipNamesFor(starNation: string, observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getShipNamesFor(starNation: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getShipNamesFor(starNation: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getShipNamesFor(starNation: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (starNation === null || starNation === undefined) {
            throw new Error('Required parameter starNation was null or undefined when calling getShipNamesFor.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/private/rpg/shipNames/${encodeURIComponent(String(starNation))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipNamesForUser(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getShipNamesForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getShipNamesForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getShipNamesForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/private/rpg/shipNames`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShipPrefix(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getShipPrefix(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getShipPrefix(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getShipPrefix(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/private/rpg/shipPrefix`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param starNation 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeShipNameTemplate(starNation: string, observe?: 'body', reportProgress?: boolean): Observable<RolePlayData>;
    public removeShipNameTemplate(starNation: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RolePlayData>>;
    public removeShipNameTemplate(starNation: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RolePlayData>>;
    public removeShipNameTemplate(starNation: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (starNation === null || starNation === undefined) {
            throw new Error('Required parameter starNation was null or undefined when calling removeShipNameTemplate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RolePlayData>('delete',`${this.basePath}/api/private/rpg/shipTemplate/${encodeURIComponent(String(starNation))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeShipNamesFor(name: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public removeShipNamesFor(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public removeShipNamesFor(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public removeShipNamesFor(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling removeShipNamesFor.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/api/private/rpg/shipNames/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeShipPrefix(observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public removeShipPrefix(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public removeShipPrefix(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public removeShipPrefix(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/api/private/rpg/shipPrefix`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the list of ship names
     * 
     * @param prefix 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setShipPrefix(prefix: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public setShipPrefix(prefix: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public setShipPrefix(prefix: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public setShipPrefix(prefix: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (prefix === null || prefix === undefined) {
            throw new Error('Required parameter prefix was null or undefined when calling setShipPrefix.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/api/private/rpg/shipPrefix/${encodeURIComponent(String(prefix))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
