/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Article } from '../model/article';
import { ArticleCreate } from '../model/articleCreate';
import { ArticleEdit } from '../model/articleEdit';
import { ArticlePlainContent } from '../model/articlePlainContent';
import { FrontendError } from '../model/frontendError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {environment} from '../../../../environments/environment';


@Injectable()
export class WikiApiService {

    protected basePath = environment.backendServer;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Creates a new article.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createArticle(body: ArticleCreate, observe?: 'body', reportProgress?: boolean): Observable<Article>;
    public createArticle(body: ArticleCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Article>>;
    public createArticle(body: ArticleCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Article>>;
    public createArticle(body: ArticleCreate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createArticle.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Article>('post',`${this.basePath}/api/private/wiki/`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Creates a new article.
     * 
     * @param body default response
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editArticle(body: ArticleEdit, observe?: 'body', reportProgress?: boolean): Observable<Article>;
    public editArticle(body: ArticleEdit, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Article>>;
    public editArticle(body: ArticleEdit, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Article>>;
    public editArticle(body: ArticleEdit, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editArticle.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Article>('put',`${this.basePath}/api/private/wiki/`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all articles.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllArticles(observe?: 'body', reportProgress?: boolean): Observable<Array<Article>>;
    public getAllArticles(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Article>>>;
    public getAllArticles(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Article>>>;
    public getAllArticles(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Article>>('get',`${this.basePath}/api/public/wiki/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns all article which are matching a left-side search for the title.
     * 
     * @param articleTitle 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getArticleForAutocomplete(articleTitle: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Article>>;
    public getArticleForAutocomplete(articleTitle: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Article>>>;
    public getArticleForAutocomplete(articleTitle: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Article>>>;
    public getArticleForAutocomplete(articleTitle: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (articleTitle === null || articleTitle === undefined) {
            throw new Error('Required parameter articleTitle was null or undefined when calling getArticleForAutocomplete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Article>>('get',`${this.basePath}/api/public/wiki/autocomplete/${encodeURIComponent(String(articleTitle))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the latest content of the requested article.
     * 
     * @param idArticle 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getArticleLatestContent(idArticle: number, observe?: 'body', reportProgress?: boolean): Observable<ArticlePlainContent>;
    public getArticleLatestContent(idArticle: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArticlePlainContent>>;
    public getArticleLatestContent(idArticle: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArticlePlainContent>>;
    public getArticleLatestContent(idArticle: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idArticle === null || idArticle === undefined) {
            throw new Error('Required parameter idArticle was null or undefined when calling getArticleLatestContent.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ArticlePlainContent>('get',`${this.basePath}/api/public/wiki/${encodeURIComponent(String(idArticle))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns all revisions of the requested article.
     * 
     * @param idArticle 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getArticleRevisions(idArticle: number, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getArticleRevisions(idArticle: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getArticleRevisions(idArticle: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getArticleRevisions(idArticle: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idArticle === null || idArticle === undefined) {
            throw new Error('Required parameter idArticle was null or undefined when calling getArticleRevisions.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('get',`${this.basePath}/api/public/wiki/revisions/${encodeURIComponent(String(idArticle))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the latest content of the requested article.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHomeArticle(observe?: 'body', reportProgress?: boolean): Observable<ArticlePlainContent>;
    public getHomeArticle(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArticlePlainContent>>;
    public getHomeArticle(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArticlePlainContent>>;
    public getHomeArticle(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ArticlePlainContent>('get',`${this.basePath}/api/public/wiki/home`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the current tick.
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPossibleLanguages(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getPossibleLanguages(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getPossibleLanguages(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getPossibleLanguages(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/public/wiki/languages`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the latest content of the requested article.
     * 
     * @param tutorialCategory 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTutorialArticle(tutorialCategory: string, observe?: 'body', reportProgress?: boolean): Observable<ArticlePlainContent>;
    public getTutorialArticle(tutorialCategory: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArticlePlainContent>>;
    public getTutorialArticle(tutorialCategory: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArticlePlainContent>>;
    public getTutorialArticle(tutorialCategory: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tutorialCategory === null || tutorialCategory === undefined) {
            throw new Error('Required parameter tutorialCategory was null or undefined when calling getTutorialArticle.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ArticlePlainContent>('get',`${this.basePath}/api/public/wiki/tutorial/${encodeURIComponent(String(tutorialCategory))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
